### ISSUE TITLE
Broken link to Fast.ai course in Unit 1 >  The “Deep” in Reinforcement Learning

### ISSUE THREAD

**Issue by zkenshin** [huggingface/deep-rl-class#102]
At the bottom of https://huggingface.co/deep-rl-course/unit1/deep-rl there is a link to "the FastAI Practical Deep Learning for Coders" course. It currently links to https://course.fast.a/, which is missing the i at the end.

The correctly link should be https://course.fast.ai/
e.g.
[the FastAI Practical Deep Learning for Coders](https://course.fast.ai/)

**Comment by simoninithomas** [comment]
Hey there 👋 . Thanks for pointing this out 🤗 We just merged it in #100
