### ISSUE TITLE
Broken cover image in Unit 1

### ISSUE THREAD

**Issue by coyotte508** [huggingface/deep-rl-class#104]
https://huggingface.co/deep-rl-course/unit1/hands-on?fw=pt#unit-1-train-your-first-deep-reinforcement-learning-agent

![image](https://user-images.githubusercontent.com/342922/205874359-4f46dd4c-92ec-4820-8742-e27e60cd4f6f.png)

**Comment by simoninithomas** [comment]
Hey there 👋 . Thanks for pointing this out 🤗 I update it

**Comment by simoninithomas** [comment]
Solved here #106 thanks again 🤗
