### ISSUE TITLE
package_to_hub not working

### ISSUE THREAD

**Issue by angelinux** [huggingface/deep-rl-class#11]
At the end of unit 1 I cannot execute the package_to_hub function.
I get the error "NameError: name 'base' is not defined" in line 235 of /usr/local/lib/python3.7/dist-packages/pyglet/gl/__init__.py

**Comment by angelinux** [comment]
Solved by putting !pip install pyglet==1.5.1 at the start and then restarting runtime on Colab

**Comment by osanseviero** [comment]
I think this should be re-opened. @angelinux would you like to open a PR adding`pyglet==1.5.1` at the top of the notebook?

**Comment by angelinux** [comment]
Done.

**Comment by CHOCO-LEO** [comment]
I am still getting the error with pyglet 1.5.1.
