### ISSUE TITLE
Leaderboard - Had to refresh the dashboard 

### ISSUE THREAD

**Issue by angellmethod** [huggingface/deep-rl-class#110]
I waited about ~6 hours to see if my Lunar Lander model from unit 1 would show up on the leaderboard. I noticed that at the very bottom it had a 'refresh' button. Once I clicked refresh my model shows on the leaderboard, but if it is necessary to click that refresh button, it would be good to add a note in the unit 1 jupyter notebook because other people will also likely wonder why their model is not showing.

**Comment by osanseviero** [comment]
Hey there! Thanks for the feedback. We'll be making some changes in the dashboard so it refreshes automatically every hour or so.

**Comment by simoninithomas** [comment]
Hey there 👋 , we update the leaderboard but for now if you don't find your model, you need to go at the bottom of the page and you need to click on the refresh button 🤗
