### ISSUE TITLE
Unit 2 - Installing requirements

### ISSUE THREAD

**Issue by Arch4ngel21** [huggingface/deep-rl-class#118]
Small issue, duplicated command, haven't seen it addressed before:

![image](https://user-images.githubusercontent.com/92851969/207355105-e3a4475e-cbdb-4c53-aba2-11aef2e87c5b.png)

I believe it should be just:

![image](https://user-images.githubusercontent.com/92851969/207355974-86d573a2-a5e6-4ab8-abb9-fc87deb528f0.png)

**Comment by simoninithomas** [comment]
Hey there 👋 . Thanks for pointing this out 🤗 I updated the notebook. I'm updating the course mdx file too.
