### ISSUE TITLE
Huggy bonus unit should use smaller checkpoint intervals

### ISSUE THREAD

**Issue by discordianfish** [huggingface/deep-rl-class#120]
The oldest checkpoint I have already received ~90% of the reward that the final trained one gets, making it hard to see any progression.
A smaller checkpoint interval would give users a 'bad' model to compare to the finially trained on.

**Comment by simoninithomas** [comment]
Hey there 👋 , so the problem is that updating checkpoint_interval to something smaller increases the upload time.
So what we can do instead of having a checkpoint of 500,000 we can change it to 200,000. I will also update the colab to mention that people can modify it.

**Comment by simoninithomas** [comment]
Done ✔️  thanks again for pointing this out 🤗
