### ISSUE TITLE
Unit 1 :: State vs Observation

### ISSUE THREAD

**Issue by andraxin** [huggingface/deep-rl-class#123]
The distinction between state and observation taught here
appears somewhat non-standard inasmuch as the latter is
*required* to be a _partial state_ here, which need not be
the case in general.  In a fully observable scenario, state
and observation are identical.

This view is *not* accepted here (cf. Quiz 1).

---
- [x]  We receive an observation when we play with chess environment
 Incorrect. Since we have access to the whole checkboard information.
---

BTW, the expected answer is incorrect even with the course's
non-standard definition requiring observations to be partial,
since chess is *not* fully observable given the current position.
See https://github.com/huggingface/deep-rl-class/issues/122

**Comment by simoninithomas** [comment]
There is 2 things: the difference between partial/fully observable and state and observation. https://www.youtube.com/watch?v=fdY7dt3ijgY
We didn't mentionned partial/fully observation It's something we put on reading list with Sutton Book.

**Comment by andraxin** [comment]
My only beef is that those 2 things are _not_ orthogonal.

Pretty much every other course or text defines observation
as partial state that _may_ omit parts of the complete state.
This _also_ includes OpenAI's Spinning Up you linked above.
https://spinningup.openai.com/en/latest/spinningup/rl_intro.html#states-and-observations

Your definition *requires* observations to be *strictly* partial,
which makes very little sense.  The distinction between full
state and potentially partial state is important, but you seem
to want to enforce an artificial exclusion here.
