### ISSUE TITLE
Missing Links in the Unit 1 jupyter notebook

### ISSUE THREAD

**Issue by this-is-ac** [huggingface/deep-rl-class#126]
## Prerequisites 🏗️
Before diving into the notebook, you need to:

🔲 📝 **Done Unit 0** that gives you all the **information about the course and help you to onboard** 🤗 ADD LINK 

🔲 📚 **Develop an understanding of the foundations of Reinforcement learning** (MC, TD, Rewards hypothesis...) by doing Unit 1 👉 ADD LINK

I guess the links haven't been added to ADD LINK, anyways I'm attaching them below so you can do the same or I would be happy to create a PR :)

https://huggingface.co/deep-rl-course/unit0/introduction
https://huggingface.co/deep-rl-course/unit1/introduction

**Comment by osanseviero** [comment]
Hey there! If you're up for it, feel free to open a PR for the Hands On mdx file in Unit 1 :) Thank you so much for the report!

**Comment by simoninithomas** [comment]
Yes don't hesitate to make a PR 🤗
