### ISSUE TITLE
[Contributions welcomed] Create a glossary for Unit 2

### ISSUE THREAD

**Issue by osanseviero** [huggingface/deep-rl-class#128]
Similar to #32 

End result: https://huggingface.co/deep-rl-course/unit1/glossary?fw=pt

**Comment by misza222** [comment]
Types of value-based policies:
 - greedy - agent chooses the state with the highest expected return
 - epsilon-greedy - with P(ϵ) random action is chosen, with P(1-ϵ) best action is chosen

Bellman Equation - recursive algorithm where value of the state equals to the immediate reward in a new state + discounted value of that new state

Learning rate - Learning strategies use learning rate α to update previous values or the function.

Learning strategries:
 - Monte Carlo - agent updates the value function at the end of the episode
 - Temporal Difference Learning - agent updates the value function whenever new information is encountered

**Comment by simoninithomas** [comment]
Hey there @misza222 👋 we have a glossary for Unit 2. But you can add some of the definitions that are not there that you wrote above 🤗. Thanks

**Comment by simoninithomas** [comment]
Closing Issue since the glossary has been updated :hugs:
