### ISSUE TITLE
Error on package_to_hub

### ISSUE THREAD

**Issue by ChechkovEugene** [huggingface/deep-rl-class#13]
CalledProcessError                        Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/huggingface_hub/repository.py](https://localhost:8080/#) in git_pull(self, rebase, lfs)
   1073                     encoding="utf-8",
-> 1074                     cwd=self.local_dir,
   1075                 )

3 frames
CalledProcessError: Command '['git', 'pull']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/huggingface_hub/repository.py](https://localhost:8080/#) in git_pull(self, rebase, lfs)
   1076                 logger.info(result.stdout)
   1077         except subprocess.CalledProcessError as exc:
-> 1078             raise EnvironmentError(exc.stderr)
   1079 
   1080     def git_add(

OSError: warning: no common commits
From https://huggingface.co/ChechkovEugene/ppo-LunarLander-v2
 + b4bcf4f...6e99bcb main       -> origin/main  (forced update)
fatal: refusing to merge unrelated histories

**Comment by simoninithomas** [comment]
Hi, I need to more information to understand the error:
- What platform did you used: the colab, your own machine (which OS?).
- Can you provide a link to the filled colab?
Thanks

**Comment by ChechkovEugene** [comment]
> Platform: Colab
Sure! Here is the link https://colab.research.google.com/drive/1szOwGegwNaiPGo7fA4QNNGLuOwfPv-lg?usp=sharing

**Comment by simoninithomas** [comment]
Sorry for the delay (feel free to send me a DM message if I don't reply in a day)
It's seems a conflict in versions of the repo. I think the best solution is to go to your colab folders (on the left) and remove "hub" and run again the package_to_hub part.
