### ISSUE TITLE
Leaderboard updates

### ISSUE THREAD

**Issue by osanseviero** [huggingface/deep-rl-class#135]
1. Auto-refresh the leaderboard everyday

This can be done with something similar to

```python
scheduler = BackgroundScheduler()
scheduler.add_job(func=refresh_leaderboard, trigger="interval", seconds=3600)
scheduler.start()
``` 

`refresh_leaderboard` should then be the function that updates the leaderboard. This was discussed internally in https://huggingface.slack.com/archives/C03G6RUSQV7/p1670496617400689?thread_ts=1670485915.587849&cid=C03G6RUSQV7

2. Add pagination to the leaderboard

Here is an example of how this can be done https://huggingface.co/spaces/ysharma/Playground_AI_Exploration

cc @freddyaboulton too

**Comment by simoninithomas** [comment]
I'm not sure for pagination. People search with Ctrl+F
I added scheduler if you can tell me what you think: https://huggingface.co/spaces/ThomasSimonini/Deep-Reinforcement-Learning-Leaderboard

Thanks 🤗
