### ISSUE TITLE
[Contributions Welcome] Write a guide using Optuna to find the best hyperparameters

### ISSUE THREAD

**Issue by osanseviero** [huggingface/deep-rl-class#14]
As a special content for Unit 1, many people have asked for an example showing Optuna to find the right hyperparameters for `PPO`. Would anyone be interested in adding one? It does not need to be a long one, just showing how to use it to find the right hyperparameters and finally pushing to the Hub.

**Comment by araffin** [comment]
There is short one for A2C that can be adapted for PPO (it is also in Optuna examples):  https://github.com/araffin/rl-handson-rlvs21/blob/main/optuna/sb3_simple.py

It comes from RLVS talk: https://youtu.be/Ikngt0_DXJg?t=11464 (it starts at 3:11:04 for hyperparameter tuning)

(I'm also preparing a longer tutorial on hyperparameter tuning that will be first shown at ICRA in 3 weeks: https://araffin.github.io/tools-for-robotic-rl-icra2022/)

**Comment by sambitmukherjee** [comment]
I've created a pull request for this. Please let me know if any modifications are required. Thanks!

**Comment by simoninithomas** [comment]
Closing this issue since I added @sambitmukherjee notebook + tomorrow we'll put on Unit 3 bonus the ICRA2022 links
