### ISSUE TITLE
Add bonus content on how to create a gym environment

### ISSUE THREAD

**Issue by osanseviero** [huggingface/deep-rl-class#142]
There are multiple requests for this. Not for now, but maybe we could add some bonus content or a bonus unit for it :)

**Comment by osanseviero** [comment]
Related feedback from Discord

> While I'm studying these two first units, there is a thought that comes to my mind... Correct me if I'm wrong: I think that when we want to apply a RL algorithm to solve a specific problem it's very important how the environment, the agent's actions and the reward are defined. If all the components aren't well defined, it probably doesn't matter how good a RL algorithm is (A2C, PPO, etc) and the solution will be poor. Would it be interesting to create a bonus-unit in which a new problem is proposed and then we try to define the environment, rewards, etc. (using the gym library, for example) and then apply the algorithms learned during the course?

**Comment by simoninithomas** [comment]
A short term solution is to add a link to the tutorial made by Gym? https://www.gymlibrary.dev/content/environment_creation/

**Comment by osanseviero** [comment]
Yes good idea!

**Comment by simoninithomas** [comment]
Added to reading list. I'm closing this issue
