### ISSUE TITLE
Typos - Unit 2 

### ISSUE THREAD

**Issue by yassinekdi** [huggingface/deep-rl-class#148]
Great tutorial. Here are some typos (I think the **[???]** part should be filled with something) : 

- Section "The two types of value-based methods" : 
"In value-based, finding an optimal value function (denoted Q* or V*, we’ll study the difference after) in **[???]** our leads to having an optimal policy."

- Section "The Bellman Equation, simplify our value estimation" : 
"To recap, the idea of the Bellman equation is that **instead** of calculating each value as the sum of the expected return, which is a long process **[???]**. This is equivalent.."

- Section "Monte Carlo vs Temporal Difference Learning" : 
The equation "Gt = Rt+1 + Rt+2 + Rt+3" in the Monte Carlo part is repeated (just below the sentence "We have a list of state, action.."
Just below the subtitle "Temporal Difference Learning: learning at each step", I don't think there is a bullet point, it's maybe the same sentence ?

**Comment by simoninithomas** [comment]
Hey there 👋 . Thanks for pointing this out 🤗 I'm updating it.

**Comment by simoninithomas** [comment]
Updated it #151 thanks again for your feedback 🤗. I'm closing the issue
