### ISSUE TITLE
Unit1 step 07 adding Callback function

### ISSUE THREAD

**Issue by theaveasso** [huggingface/deep-rl-class#15]
Knowing how to Save/Load the model is great. Could we add a callback function, CallbackList, CheckpointCallback, and EvalCallback? Thanks

**Comment by simoninithomas** [comment]
Hi (sorry for the big delay), thanks for the feedback. we provide for now a link towards Antonin's RL best practices and there's a step about creating your own Callbacks. We think that for the first unit that would be too much for people that's why we added it as additional resource. 🤗
