### ISSUE TITLE
[Contributions welcomed] Create a glossary for Unit 3

### ISSUE THREAD

**Issue by misza222** [huggingface/deep-rl-class#150]

**Comment by misza222** [comment]
temporal information - how things change through time

**Comment by simoninithomas** [comment]
Hey there 👋 , can you open a PR to put the definitions so that then we will be able to merge and people can iterate on it 🤗
Thanks

**Comment by simoninithomas** [comment]
A glossary has been created in #168 I'm closing this issue then. Thanks 🤗
