### ISSUE TITLE
Finding My Trained model in spaces is too harder!

### ISSUE THREAD

**Issue by dhakalnirajan** [huggingface/deep-rl-class#153]
Hi! I just finished my first unit of Deep RL course. I deployed the model in the HF. When I went to Thomas's Huffy Space, I scrolled for half an hour to find my model and I still can't get it. Is there something I am missing or can something be done to find model by search method?

If it helps, [here is my model link](https://huggingface.co/nirajandhakal/Huggy-the-dog).

**Comment by simoninithomas** [comment]
Hey there 👋 I'm trying to solve the issue today.Thanks for pointing this out 🤗 . I keep you updated

**Comment by simoninithomas** [comment]
Hey there 👋 ,

We just updated Huggy 🐶  with your feedback 🤗

1️⃣ The models are now ordered in alphabetical order.
2️⃣  We added a slider to scroll + increased the scroll speed.
