### ISSUE TITLE
Typos unit 3

### ISSUE THREAD

**Issue by ramon-rd** [huggingface/deep-rl-class#154]
Amazing tutorial! Here are some typos:

- The automatic hyperparameter tuning with optuna bonus should be "Bonus Unit 3" instead of "Unit Bonus 2"?
- The introduction and From Q-Learing to Deep Q-Learning sections say that the FrozenLake-v1 has 14 different states and should be 16.

Should I made a pull request?

**Comment by simoninithomas** [comment]
Hey there 👋 . Thanks for pointing this out 🤗 if you can yes please that would help 🤗

**Comment by simoninithomas** [comment]
Solved in #171 closing the issue thanks again 🤗
