### ISSUE TITLE
change current working directory before starting train.py

### ISSUE THREAD

**Issue by munterwexi** [huggingface/deep-rl-class#155]
In the colab notebook it is necessary to change the current working directory from '/content' to '/content/rl-baselines3-zoo' where the train.py file is located.

done by: 

import os
os.chdir('/content/rl-baselines3-zoo')

insert before line 
!python train.py --algo dqn  --env SpaceInvadersNoFrameskip-v4 -f logs/

**Comment by simoninithomas** [comment]
Hey there :wave: I suppose you talk about the old version of the notebook, this has been updated in v2. Thanks for pointing this out :hugs:  I'm closing the issue.
