### ISSUE TITLE
Unit 3 juypter notebook link to .yml config file

### ISSUE THREAD

**Issue by renee127** [huggingface/deep-rl-class#158]
First, thank you for this excellent course!

Minor suggestion to allow the opening of the text edit sidebar for parameter changes.

In ## Train our Deep Q-Learning Agent to Play Space Invaders 👾 section:

Change
1. We define the hyperparameters in `rl-baselines3-zoo/hyperparams/dqn.yml`

to
1. We define the hyperparameters in `/content/rl-baselines3-zoo/hyperparams/dqn.yml`

Cheers

**Comment by simoninithomas** [comment]
Updated in #231 thanks again 🤗
