### ISSUE TITLE
Logging with tensorboard and wandb

### ISSUE THREAD

**Issue by SuperSecureHuman** [huggingface/deep-rl-class#16]
Hey there!

I would like to make a notebook which helps others get started with logging of their experiments with tensorboard and wandb, along with pushing the logs to hub.

**Comment by osanseviero** [comment]
Sounds great! Would it make sense to have them as two separate notebooks? (one showing tensorboard logging and one showing wandb) I think the wandb might require a bit of additional setup and maybe it would make sense to keep the split.

**Comment by bguan** [comment]
Great idea, i was wondering how one might use these to experiment with different models and tune the various parameters. It would be great if the course could cover how to effectively tune models e.g. how to use logging and graphing to achieve this.

**Comment by SuperSecureHuman** [comment]
Thanks for merging the PR! (https://github.com/huggingface/deep-rl-class/pull/19)

Closing the issue now :)
