### ISSUE TITLE
Unit 1 - AttributeError: 'DummyVecEnv' object has no attribute 'render_mode'

### ISSUE THREAD

**Issue by felipeoliverai** [huggingface/deep-rl-class#164]
I don't know what is happening, something is wrong in the notebook on unit 1: https://colab.research.google.com/github/huggingface/deep-rl-class/blob/master/notebooks/unit1/unit1.ipynb#scrollTo=xMkkkukIBQJM

when I try to push my Agent to HF Hub I received this error message: AttributeError: 'DummyVecEnv' object has no attribute 'render_mode'

my code is very similar to the notebook example. the only difference is the repo name where I replace by my own.

**Comment by simoninithomas** [comment]
Hey there 👋 as mentioned on discord.
"I run entirely the notebook and I've got no bugs.
That might come from the fact that you've got a crash. So the library are not loaded anymore https://huggingface.co/ThomasSimonini/ppo-LunarLander-v2-2222222222 (I've trained an horrible lunar lander by the way 😆 )"

So I think it's either a crash of the notebook so the library are not loaded. Or one of the cell was not runned (did you run virtual screen?).

If you provide me your custom notebook link I can check.

**Comment by felipeoliverai** [comment]
Hey! that is exactly what you said @simoninithomas, after the agent is trained the google collab crash and libraries are unloaded, the solution is to load again the libraries and run the notebook once again. it's a google colab bug. 

Thank you for your support @simoninithomas 😉
