### ISSUE TITLE
NameError: name 'base' is not defined when running package_to_hub()

### ISSUE THREAD

**Issue by WesleyPasfield** [huggingface/deep-rl-class#169]
Was able to resolve with `!pip3 install pyglet==1.5.11` , but until then would error out in Google Colab.

**Comment by simoninithomas** [comment]
Hey there 👋 , it was on which unit?

**Comment by WesleyPasfield** [comment]
Hey! Unit 1, the notebook name is unit1.ipynb, link to access: https://colab.research.google.com/github/huggingface/deep-rl-class/blob/master/notebooks/unit1/unit1.ipynb from this page: https://huggingface.co/deep-rl-course/unit1/hands-on?fw=pt

**Comment by simoninithomas** [comment]
Thanks I added pyglet to the requirement.txt I'm closing the issue 🤗
