### ISSUE TITLE
model_name must not have an extension

### ISSUE THREAD

**Issue by andreinechaev** [huggingface/deep-rl-class#18]
If a user sets `model_name` with an extension, `model.save(name)` won't append `.zip`. The course's internal tooling appends `.zip` to the name despite the content. As the outcome there will be an error that the file was not found. 
Steps to reproduce.
```python
model_name = 'my_model.ext'
model.save(model_name)

package_to_hub(model, model_name=model_name, ...)
```
this will return an error that `my_model.ext.zip` does not exist.

**Comment by simoninithomas** [comment]
Hi @andreinechaev sorry for the delay response we updated the package_to_hub version, we don't have this bug anymore.

Thanks for pointing it out 🤗 

Have a nice day,
