### ISSUE TITLE
Unit 4 Typos

### ISSUE THREAD

**Issue by dario248** [huggingface/deep-rl-class#180]
- **Objective Function section**: https://huggingface.co/deep-rl-course/en/unit4/policy-gradient?fw=pt#the-objective-function
Letter theta is not displaying correctly
> J(θ) : Expected return, we calculate it by summing for all trajectories, the probability of taking that trajectory given $\theta$, and the return of this trajectory.

- I think **reward** should be singular
>Our objective then is to maximize the expected cumulative **rewards** by finding \thetaθ that will output the best action probability distributions 

- (Optional) The Policy Gradient Theorem: https://huggingface.co/deep-rl-course/en/unit4/pg-theorem?fw=pt#optional-the-policy-gradient-theorem
There is one missing term in the following equations:
 
$\nabla_\theta log P(\tau^{(i)};\theta)= \nabla_\theta \left[ \sum\limits_{t=0}^{H}log P(s_{t+1}^{(i)}|s_{t}^{(i)} a_{t}^{(i)}) + \sum\limits_{t=0}^{H}log \pi_\theta(a_{t}^{(i)}|s_{t}^{(i)})\right]$

$\nabla_\theta log P(\tau^{(i)};\theta)= \nabla_\theta \sum\limits_{t=0}^{H} log P(s_{t+1}^{(i)}|s_{t}^{(i)} a_{t}^{(i)}) + \nabla_\theta \sum\limits_{t=0}^{H} log \pi_\theta(a_{t}^{(i)}|s_{t}^{(i)})$

Correct equations:

$\nabla_\theta log P(\tau^{(i)};\theta)= \nabla_\theta \left[log \mu(s_0) + \sum\limits_{t=0}^{H}log P(s_{t+1}^{(i)}|s_{t}^{(i)} a_{t}^{(i)}) + \sum\limits_{t=0}^{H}log \pi_\theta(a_{t}^{(i)}|s_{t}^{(i)})\right]$

$\nabla_\theta log P(\tau^{(i)};\theta)=\nabla_\theta log\mu(s_0) + \nabla_\theta \sum\limits_{t=0}^{H} log P(s_{t+1}^{(i)}|s_{t}^{(i)} a_{t}^{(i)}) + \nabla_\theta \sum\limits_{t=0}^{H} log \pi_\theta(a_{t}^{(i)}|s_{t}^{(i)})$

**Comment by simoninithomas** [comment]
Big update merged thanks :hugs:
