### ISSUE TITLE
Problem installing requirements from Unit 1

### ISSUE THREAD

**Issue by avoroshilov** [huggingface/deep-rl-class#186]
Disclaimer: I am using local setup, and even more - Win10-based. I had some issues with installing requirements from https://huggingface.co/spaces/ThomasSimonini/temp-space-requirements/raw/main/requirements/requirements-unit1.txt

Specifically, this was the error:
```
Collecting AutoROM.accept-rom-license
  Using cached AutoROM.accept-rom-license-0.5.0.tar.gz (10 kB)
  
  Building wheel for AutoROM.accept-rom-license (pyproject.toml) ... error
  error: subprocess-exited-with-error

            import libtorrent as lt
      ImportError: DLL load failed while importing libtorrent: The specified module could not be found.
```

After fiddling with the libraries not in the path, I've managed to make `libtorrent` work locally, but unfortunately it was still failing in `pip install`. I've checked the requirements for the `stable-baselines3[extra]` / `ale`, and apparently it needs `AutoROM.accept-rom-license>=0.4.2`, so I tried installing `0.4.2` explicitly, and it worked. I was using **stable-baselines3 1.6.2** at the time.

So the question is - can `AutoROM.accept-rom-license==0.4.2` be added at the beginning of the https://huggingface.co/spaces/ThomasSimonini/temp-space-requirements/raw/main/requirements/requirements-unit1.txt - and maybe then it would be worthwhile to fix the SB3 version too?

**Comment by avoroshilov** [comment]
This actually is addressed to some extent with this PR: https://github.com/huggingface/deep-rl-class/pull/167, specifically this line: https://github.com/huggingface/deep-rl-class/pull/167/files#diff-44294af9c6162c180a374ddca42cf9c1a4320defdd0d808c0174c65ef9adb758R234

**Comment by simoninithomas** [comment]
Closing this issue since we updated the notebook 🤗
