### ISSUE TITLE
HTML element not being rendered correctly in Unit 1

### ISSUE THREAD

**Issue by rodrigomeireles** [huggingface/deep-rl-class#187]
https://huggingface.co/deep-rl-course/unit1/hands-on?fw=pt

We see the following:

![image](https://user-images.githubusercontent.com/39929801/211231139-cd0bedf5-7a31-4031-8aa5-06c3f23e0839.png)

Pretty sure this is not the intended behaviour.

**Comment by simoninithomas** [comment]
Thanks for pointing this out I'm adding that to the next batch of updates next week 🤗

**Comment by simoninithomas** [comment]
Solved in #230 thanks :hugs:
