### ISSUE TITLE
New version of gym, gymnasium

### ISSUE THREAD

**Issue by allansuzuki** [huggingface/deep-rl-class#188]
url: https://gymnasium.farama.org/

It'seems gym will not be the latest package update anymore.
Gymnaisum will be the newest one.
The topic is just to make u know and perhaps update the notebooks with the updated version :)

**Comment by simoninithomas** [comment]
Hey there 👋 , for the next units we're going to use gymnasium but some environments (Pybullet) are still not compatible with it.
I'm adding it to the next update to add information about gymnasium. Thanks 🤗
