### ISSUE TITLE
Unit 1 Hands-on prerequisites 

### ISSUE THREAD

**Issue by PatrykNeubauer** [huggingface/deep-rl-class#192]
Prerequisites of Unit 1 hands-on mention Monte Carlo and TD-Learning, that are covered later in Unit 2 - they're not even mentioned in Unit 1.
Might be bit confusing for some people, perhaps it'd be better to delete that.

<img width="623" alt="Screenshot 2023-01-11 103420" src="https://user-images.githubusercontent.com/62596795/211771071-15f84834-1134-4690-b436-dcd6cc237c40.png">

https://huggingface.co/deep-rl-course/unit1/hands-on?fw=pt#prerequisites

**Comment by simoninithomas** [comment]
Thanks for pointing this out I'm adding it to next week update 🤗

**Comment by simoninithomas** [comment]
Solved in #230 thanks :hugs:
