### ISSUE TITLE
ML-Agents results not on leaderboard

### ISSUE THREAD

**Issue by c1505** [huggingface/deep-rl-class#193]
I noticed the ML-Agents results are not on the leaderboard.  Feel free to close this if the decision was made to not include them.

**Comment by simoninithomas** [comment]
Hey there 👋 , yes the MLAgents are not on the leaderboard because we don't have an evaluation tool yet for MLAgents we're working on it 🤗

**Comment by simoninithomas** [comment]
Hey there 👋 which model? If it's AI vs AI we have a leaderboard. Else we don't plan to add an evaluation tool for MLAgents for now.

**Comment by Karlheinzniebuhr** [comment]
> Hey there 👋 which model? If it's AI vs AI we have a leaderboard. Else we don't plan to add an evaluation tool for MLAgents for now.

Hi! [this model](https://huggingface.co/Karlpy/LunarLander-v2) it should appear in [this leaderboard](https://huggingface.co/spaces/huggingface-projects/Deep-Reinforcement-Learning-Leaderboard) afaik

**Comment by simoninithomas** [comment]
Hey there 👋 your model is on the leaderboard https://huggingface.co/spaces/huggingface-projects/Deep-Reinforcement-Learning-Leaderboard we just display the first 100 models but if you type your user id in the search bar Karlpy you'll find them (rank 42 and rank 1230)

**Comment by Karlheinzniebuhr** [comment]
Now I can see it! Had to wait for 24h it seems, thank you! :)
