### ISSUE TITLE
bug on Unit 6

### ISSUE THREAD

**Issue by SatCat** [huggingface/deep-rl-class#197]
Hi!
On unit6, at 'Evaluate the agent' code:
...
eval_env.norm_reward = False
model = A2C.load("a2c-AntBulletEnv-v0")
mean_reward, std_reward = evaluate_policy(model, env)    # <-- eval_env?!

I think in last line we need to use eval_env, not env.

**Comment by simoninithomas** [comment]
Indeed thanks for pointing this out I update it 🤗

**Comment by simoninithomas** [comment]
Updated thanks I close this issue 🤗
