### ISSUE TITLE
OS Error when attempting to push trained agent using package_to_hub() function

### ISSUE THREAD

**Issue by StanKarz** [huggingface/deep-rl-class#20]
The following error is shown when attempting to push the trained agent using the package_to_hub() function:

For reference I am using Google Colab and Mac OS Big Sur 11.5.2

CalledProcessError: Command '['git', 'pull']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)

[/usr/local/lib/python3.7/dist-packages/huggingface_hub/repository.py](https://localhost:8080/#) in git_pull(self, rebase, lfs)
   1076                 logger.info(result.stdout)
   1077         except subprocess.CalledProcessError as exc:
-> 1078             raise EnvironmentError(exc.stderr)
   1079 
   1080     def git_add(

OSError: warning: no common commits
From https://huggingface.co/Sicko-Code/PPO-lunarlander-v2
 + 3823c08...4b3486e main       -> origin/main  (forced update)
fatal: refusing to merge unrelated histories

**Comment by nateraw** [comment]
In what scenario did this happen? Did you already have something pushed up to that repo and you were trying to update it? Perhaps from a different local copy? I think perhaps adding `rebase=True` to the `repo.git_clone` in `huggingface_sb3` could fix this problem in the future...I'll PR it.

**Comment by simoninithomas** [comment]
I'm closing the issue, we updated the huggingface_sb3 repo 🤗
