### ISSUE TITLE
Bug in unit 6

### ISSUE THREAD

**Issue by olavomendes** [huggingface/deep-rl-class#200]
Hi,

In the **Normalize observation and rewards** section we have the following instructions:
- "We also normalize rewards with this same wrapper by adding `norm_reward = True`", in the text;
- "`#Adding this wrapper to normalize the observation and the reward`", in the code comment,

However, in the solution block, the code sets the `norm_reward `to `False`:

`env = VecNormalize(env, norm_obs=True, norm_reward=False, clip_obs=10.)`

Was this a mistake?

Thanks for listening.

**Comment by simoninithomas** [comment]
Updated in #231 thanks again for pointing this out 🤗
