### ISSUE TITLE
Huggy select a model is not practical

### ISSUE THREAD

**Issue by kyoussef** [huggingface/deep-rl-class#201]
When the Huggy game loaded, tried to select a model repo, it seems the list of models repositories is huge and scrolling down to find my repo was very hard, considering that filtering is not enabled. It also seemed to consume a lot of CPU time considering maybe the amount of repos loaded into the dropdown. Maybe its better to make it a text box where each user just enters his/her repo.

**Comment by simoninithomas** [comment]
Hey there 👋 do you see the right handle to move faster on the list? If not can you tell me which size of screen you're using. Normally it's just a list of text so it shouldn't take a lot of CPU. What's taking a lot of CPU is when you load a huggy since the inference is quite heavy.
