### ISSUE TITLE
Unit 4- Strange HTML $\ on the "Hands on" -> "why do we minimize the loss"

### ISSUE THREAD

**Issue by bonadio** [huggingface/deep-rl-class#204]
Hi

In Unit 4 -> Hands on ->  "why do we minimize the loss"  explanation shows some strange text those $\ 
 
![Screen Shot 2023-01-24 at 2 35 49 PM](https://user-images.githubusercontent.com/7820306/214368443-79f63cb1-f0f5-4c5f-98ba-5c85308494ec.png)

Are those \$ text supposed to show like that? 

I am using a Macbook with BigSur on a Chrome browser, tested with Safari has the same result.

**Comment by bonadio** [comment]
One update, opening the Notebook on Colab, shows the correct text

![Screen Shot 2023-01-24 at 3 07 42 PM](https://user-images.githubusercontent.com/7820306/214373484-af1ed160-b6f2-4403-8033-cdadb994dad8.png)

**Comment by simoninithomas** [comment]
Updated in #231 thanks again for pointing this out 🤗
