### ISSUE TITLE
Pushing Trained Agent to Hub - Unit1

### ISSUE THREAD

**Issue by PeriRamm** [huggingface/deep-rl-class#205]
Hello,
When trying to run the cell for pushing to the hub, I am getting error messages from the `package_to_hub` function.
Please keep in mind all the other cells run smoothly up to that point.

I have tried the 'try it yourself' cell, filling in details, the message was "NoSuchDisplayException: Cannot connect to "None"" (left side of the screenshot)
I also tried the 'solution' cell, (changing repo_id of course) and the message was "NameError: name 'base' is not defined" (right side of the screenshot)

Looking forward for a solution, as I am eager to complete the course before the deadlines.

Thanks!
![PushTo_HF_Hub_error](https://user-images.githubusercontent.com/19927743/214567296-7e21eff8-311a-4b3e-85ef-5d8b0a30cff4.jpg)

**Comment by simoninithomas** [comment]
Hey there :wave: , this is a common problem, you need to restart the notebook. What it simply means for the left one is that you didn't run a virtual screen and the second that you need to restart the virtual screen
