### ISSUE TITLE
Unit 7 - Self-Play : Typo error

### ISSUE THREAD

**Issue by RegisGraptin** [huggingface/deep-rl-class#213]
In the [Unit 7, in the Self-Play part](https://huggingface.co/deep-rl-course/unit7/self-play), I think there is an error in the example for computing the ELO score.

For the equation after the line:
"If the organizers determined that K=16 and A wins, the new rate would be:"

In the second equation it should be the loss of the player B. Thus, it should be 
ELOb = 2300 + 16 * (**0** - 0.151) = 2298

It should be 0 instead of 1, right ?

Or maybe I missed something ^^

**Comment by kinkpunk** [comment]
Right, the result second equation will be correct with 0.
![Screenshot Hugging Face Course](https://user-images.githubusercontent.com/46870761/216454133-c1b61053-3b23-4699-8f5e-65f0337ae0d2.png)

**Comment by simoninithomas** [comment]
Oh yes good catch I'm updating it :hugs:

**Comment by simoninithomas** [comment]
Done :heavy_check_mark:  thanks
