### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by StrangeTcy** [huggingface/deep-rl-class#217]
At the moment Google Colab offers me exactly zero compute units in an effort to force me to purchase a subscription.
The problems with this are:
* I disagree with their pricing policies, and
* even if I did try purchasing some compute units,   they're unavailable in my country. 
I could try buying a Cloud VM instead, but that's a separate issue.
One consequence of this is making the [`Google Colab (free version): most of our hands-on will use Google Colab, the free version is enough.`](https://huggingface.co/deep-rl-course/unit0/introduction)  line untrue in a subtle and not-immediately-obvious manner.

My suggestion is:
* switching to Kaggle, which (at the time of posting this, at least) is actually free and available to most people
* posting the minimum required specifications of a machine that would actually be able to run the example code.

**Comment by simoninithomas** [comment]
Hey there 👋 , a simple solution (that I use) is to create a new google account. I don't understand why you don't have access to simple GPU with free version I used only free version to make/train the colabs.

The second solution is simply download the colabs as ipynb and run it with jupyter notebook.

**Comment by StrangeTcy** [comment]
Freshly created google accounts don't get any compute units. You're supposed to subscribed anyway.

The second solution implies having a machine that can run the code in a jupyter notebook. These are the types of machine that google used to provide (albeit with a measly K80) and that people don't necessarily have on their own.

Anyway, I guess anyone with the same problem would be well advised to upload these notebooks to kaggle.
It might require some tweaking, but at least they'd work
