### ISSUE TITLE
Unit 1 Policy based Method - Formula unclear on dark mode

### ISSUE THREAD

**Issue by shashankgarewal** [huggingface/deep-rl-class#218]
There is an issue display the image of formula for 'action = policy(state)'
Source: https://huggingface.co/deep-rl-course/unit1/two-methods
Image Snippet:
![image](https://user-images.githubusercontent.com/42548072/217035329-4445d6ea-7368-4936-85b1-d6ff330d8e48.png)

**Comment by simoninithomas** [comment]
Updated in #231 thanks again for pointing this out 🤗
