### ISSUE TITLE
Unit 3 - Install dependencies ERROR

### ISSUE THREAD

**Issue by danielclark00** [huggingface/deep-rl-class#219]
The requirements.txt file should be updated to fix this dependency error. 
See error below:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.9.0 requires jedi>=0.10, which is not installed.
notebook 5.7.16 requires jinja2<=3.0.0, but you have jinja2 3.1.2 which is incompatible.
flask 1.1.4 requires click<8.0,>=5.1, but you have click 8.1.3 which is incompatible.
flask 1.1.4 requires Jinja2<3.0,>=2.10.1, but you have jinja2 3.1.2 which is incompatible.

**Comment by simoninithomas** [comment]
Hey there :wave: this is RL-Baselines3 Zoo requirements.txt so we can't modify it and these are not critical errors, aka you can continue the process in the colab without problem.

If you want to see how to improve the requirements.txt don't hesitate to open a PR to RL-Baselines3-Zoo :hugs:
