### ISSUE TITLE
No such file or directory: 'Xvfb'

### ISSUE THREAD

**Issue by allansuzuki** [huggingface/deep-rl-class#221]
RL Course: unit 4 (and others that uses the same code)

ERROR IN:

`# Virtual display
from pyvirtualdisplay import Display

virtual_display = Display(visible=0, size=(1400, 900))
virtual_display.start()`

xvfb package crashed:

Log:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-2-6a8c1d860fe4>](https://localhost:8080/#) in <module>
      2 from pyvirtualdisplay import Display
      3 
----> 4 virtual_display = Display(visible=0, size=(1400, 900))
      5 virtual_display.start()

5 frames
[/usr/local/lib/python3.8/dist-packages/pyvirtualdisplay/display.py](https://localhost:8080/#) in __init__(self, backend, visible, size, color_depth, bgcolor, use_xauth, retries, extra_args, manage_global_env, **kwargs)
     52             raise ValueError("unknown backend: %s" % self._backend)
     53 
---> 54         self._obj = cls(
     55             size=size,
     56             color_depth=color_depth,

[/usr/local/lib/python3.8/dist-packages/pyvirtualdisplay/xvfb.py](https://localhost:8080/#) in __init__(self, size, color_depth, bgcolor, use_xauth, fbdir, dpi, retries, extra_args, manage_global_env)
     42         self._dpi = dpi
     43 
---> 44         AbstractDisplay.__init__(
     45             self,
     46             PROGRAM,

[/usr/local/lib/python3.8/dist-packages/pyvirtualdisplay/abstractdisplay.py](https://localhost:8080/#) in __init__(self, program, use_xauth, retries, extra_args, manage_global_env)
     83         self._retries_current = 0
     84 
---> 85         helptext = get_helptext(program)
     86         self._has_displayfd = "-displayfd" in helptext
     87         if not self._has_displayfd:

[/usr/local/lib/python3.8/dist-packages/pyvirtualdisplay/util.py](https://localhost:8080/#) in get_helptext(program)
     11 
     12     # py3.6 also
---> 13     p = subprocess.Popen(
     14         cmd,
     15         stdout=subprocess.PIPE,

[/usr/lib/python3.8/subprocess.py](https://localhost:8080/#) in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors, text)
    856                             encoding=encoding, errors=errors)
    857 
--> 858             self._execute_child(args, executable, preexec_fn, close_fds,
    859                                 pass_fds, cwd, env,
    860                                 startupinfo, creationflags, shell,

[/usr/lib/python3.8/subprocess.py](https://localhost:8080/#) in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, start_new_session)
   1702                     if errno_num != 0:
   1703                         err_msg = os.strerror(errno_num)
-> 1704                     raise child_exception_type(errno_num, err_msg, err_filename)
   1705                 raise child_exception_type(err_msg)
   1706 

FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'

**Comment by allansuzuki** [comment]
Running this:
`!apt install xvfb`

got error:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-510
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  xvfb
0 upgraded, 1 newly installed, 0 to remove and 27 not upgraded.
Need to get 780 kB of archives.
After this operation, 2,271 kB of additional disk space will be used.
Ign:1 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 xvfb amd64 2:1.20.13-1ubuntu1~20.04.5
Err:1 http://security.ubuntu.com/ubuntu focal-updates/universe amd64 xvfb amd64 2:1.20.13-1ubuntu1~20.04.5
  404  Not Found [IP: 91.189.91.38 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/x/xorg-server/xvfb_1.20.13-1ubuntu1~20.04.5_amd64.deb  404  Not Found [IP: 91.189.91.38 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?


Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-510
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  xvfb
0 upgraded, 1 newly installed, 0 to remove and 27 not upgraded.
Need to get 780 kB of archives.
After this operation, 2,271 kB of additional disk space will be used.
Ign:1 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 xvfb amd64 2:1.20.13-1ubuntu1~20.04.5
Err:1 http://security.ubuntu.com/ubuntu focal-updates/universe amd64 xvfb amd64 2:1.20.13-1ubuntu1~20.04.5
  404  Not Found [IP: 91.189.91.38 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/universe/x/xorg-server/xvfb_1.20.13-1ubuntu1~20.04.5_amd64.deb  404  Not Found [IP: 91.189.91.38 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by allansuzuki** [comment]
I'm not a ubuntu user, but with tries and errors, it did work:

`!sudo apt update`
 and all the previous packages were installed successfully.

**Comment by simoninithomas** [comment]
Hey there :wave: , Xvfb is when you use Colab (since you don't have a screen it' s a virtual screen that allows us to generate a replay video). So usually when you use Ubuntu or Mac or windows you don't need it.
