### ISSUE TITLE
Unit 2: Q-Learning with FrozenLake - unclear instructions

### ISSUE THREAD

**Issue by eryzml** [huggingface/deep-rl-class#224]
In the Colab notebook for Unit 2 Hands-on the instructions are a bit unclear on cell 9. The task is to _"create our Qtable...and initialize each values at 0 using np.zeros."_ 

![Screenshot](https://user-images.githubusercontent.com/109424008/218942377-9ec394ac-f85b-49b5-89e8-2d1d05d157f6.png)

Prior to this there is no indication of how numpy is used to create a Qtable (just that it will be used in this manner). If a user is not already familiar with numpy.zeros they will likely not understand that this function "returns a multi-dimensional array in the shape of the arguments given and filled with zeros." Also that the function requires a tuble of ints in this case. It would be difficult to complete the task without relying on the solution. Perhaps it could be worded better?

> \#  Let's create our Qtable and initialize each value to 0 using np.zeros. Pass in the state_space and action_space as a tuple to np.zeroes to get a new array to use as our Qtable

**Comment by simoninithomas** [comment]
Hey there 👋 , good idea I'm adding it to the next update 🤗

**Comment by simoninithomas** [comment]
(Keep you updated when it's done)

**Comment by simoninithomas** [comment]
Updated in #231 thanks again for pointing this out 🤗
