### ISSUE TITLE
unit 8.2 - python dependencies

### ISSUE THREAD

**Issue by toinsson** [huggingface/deep-rl-class#233]
I am running into some issues with the colab notebook: there is no apparent learning, the fps is always 0.
After a while, we can read:

`Components take too long to start ... Aborting the experiments`

Troubleshooting this issue by running locally shows other error messages:

`Unhandled exception __init__() takes exactly 2 positional arguments (1 given) in evt loop batcher_evt_loop`
`  File "faster_fifo.pyx", line 30, in faster_fifo.TLSBuffer.__init__`
`TypeError: __init__() takes exactly 2 positional arguments (1 given)`

The problems comes from a new version of faster_fifo (and/or sample_factory), both of which have seen recent releases.

I used:
```
sample-factory==2.0.2
vizdoom
protobuf==3.20.*
faster-fifo==1.4.2
```
as a more precise python requirements, and it now works as intended.

This was also tested in colab notebook.
Might be good to update the colab notebook cell, and freeze the versions with:

```
# install python libraries
!pip install sample-factory==2.0.2
!pip install faster-fifo==1.4.2
!pip install vizdoom
```

**Comment by simoninithomas** [comment]
Thanks for the info I'm updating the colab 🤗

**Comment by simoninithomas** [comment]
Updated I'm closing the issue 🤗
