### ISSUE TITLE
Unit 2 - Monte Carlo vs Temporal Difference Learning

### ISSUE THREAD

**Issue by taleslimaf** [huggingface/deep-rl-class#235]
At the end of Monte Carlo, you could put an example of updating a state other than 0. Furthermore, if it were to start from the last state of the episode, we could also use Bellman's equation to update all the states as an example.

**Comment by simoninithomas** [comment]
Hey there 👋 ,
Sorry for the delayed response. That's an idea we had in mind to improve the understanding of this topic. I'm adding it to next month update.
