### ISSUE TITLE
Unit 5 issue with unity mlagents and python 3.9 compatibility in colab 

### ISSUE THREAD

**Issue by dineshresearch** [huggingface/deep-rl-class#236]
Refer here regarding details : https://github.com/Unity-Technologies/ml-agents/issues/5756

As a workaround we can downgrade the python version to 3.8 or 3.7 in colab

**Comment by DanielPuentee** [comment]
I am trying to downgrade the python version in google colab, **but it does not change.** 

Could you please send the piece of code that you use to make these changes?

**Comment by bterrific2008** [comment]
Try using the `[hf-integration](https://github.com/huggingface/ml-agents/tree/hf-integration)` branch. This seems to be the latest version of HF ml-agents' fork ([pull request here](https://github.com/Unity-Technologies/ml-agents/pull/5856))

**Comment by DanielPuentee** [comment]
Thank you. It has worked properly! 👏

**Comment by MarkieMark** [comment]
specifically, from the looks of it
change the git clone commands to
```
%%capture
# Clone the repository
!git clone --depth 1 --no-single-branch https://github.com/huggingface/ml-agents/ 
```
then change the pip install commands to
```
%%capture
# Go inside the repository and install the package
%cd ml-agents
!git checkout hf-integration
!pip3 install -e ./ml-agents-envs
!pip3 install -e ./ml-agents
```

**Comment by simoninithomas** [comment]
We updated the hands-on to install hf-integration instead thanks for pointing this out 🤗
