### ISSUE TITLE
Unit 1 - box2d dependency error

### ISSUE THREAD

**Issue by aaronrmm** [huggingface/deep-rl-class#239]
In trying to run Unit 1's collab notebook I ran into the error (as described in this [stackoverflow](https://stackoverflow.com/questions/50037674/attributeerror-module-box2d-has-no-attribute-rand-limit-swigconstant)):

AttributeError: module '_Box2D' has no attribute 'RAND_LIMIT_swigconstant'

The collab setup was installing an old version of box2d==2.3.2 and box2d-kengz==2.3.3.
The solution we found was to instead install gym[all] which installed box2d-py==2.3.5.

Presumably gym[BOX2D] might also work.

**Comment by aaronrmm** [comment]
I see now there are three PRs that address this issue. I just didn't see any Issues issues specifically for this.
https://github.com/huggingface/deep-rl-class/pull/238
https://github.com/huggingface/deep-rl-class/pull/237
https://github.com/huggingface/deep-rl-class/pull/167 ~ish

**Comment by simoninithomas** [comment]
Just merged it thanks for pointing this out, I'm testing the result but don't hesitate to open an issue if this bug is still there
