### ISSUE TITLE
Unit 1 - Issue when executing the notebook locally with the generation of the video

### ISSUE THREAD

**Issue by sachaguer** [huggingface/deep-rl-class#241]
Hello,

I've been through the notebook of the first unit and at the beginning we install packages to create a virtual screen and visualize the simulation. I was not able to install python-opengl with apt install so I did it with pip but when I want to push my code at the end it returns an error: name 'base' is not defined which seems linked to pyglet.

Did you already meet this error? How can it be sorted out?

Best,

Sacha

**Comment by simoninithomas** [comment]
Hey there 👋 , if you execute the notebook locally you normally don't need to install a virtual screen given you have a real screen. Did you tried without installing pyglet/xvfb?

**Comment by kikijiki** [comment]
I'm running on colab and have the same issue

```
NameError                                 Traceback (most recent call last)
[<ipython-input-23-4ef9b0c9bf0f>](https://localhost:8080/#) in <module>
     23 
     24 # method save, evaluate, generate a model card and record a replay video of your agent before pushing the repo to the hub
---> 25 package_to_hub(model=model, # Our trained model
     26                model_name=model_name, # The name of our trained model
     27                model_architecture=model_architecture, # The model architecture we used: in our case PPO

9 frames
[/usr/local/lib/python3.9/dist-packages/pyglet/gl/__init__.py](https://localhost:8080/#) in <module>
    233 elif compat_platform == 'darwin':
    234     from .cocoa import CocoaConfig as Config
--> 235 del base  # noqa: F821
    236 
    237 

NameError: name 'base' is not defined
```

**Comment by simoninithomas** [comment]
Closing the issue for now (stale) don't hesitate to reopen it if you still have the problem 🤗
