### ISSUE TITLE
Unit 5 - Python can't run assignment due to Python version 

### ISSUE THREAD

**Issue by joaopedrosdmm** [huggingface/deep-rl-class#246]
Hey I'm trying to do Unit 5 hands-on in Colab and every time I try to train my agent I get and error.
Can you please help out, I'm at a lost here. I think I have done every thing as instructed. 
This is the error message: https://codeshare.io/EBEvKp 
Any help with be most appreciated.

**Comment by simoninithomas** [comment]
Hey there 👋 ,
Two questions:
1. You run the code on the google colab directly?
2. Which version of MLAgents did you installed?

**Comment by joaopedrosdmm** [comment]
He
