### ISSUE TITLE
Unit 1: Requirements.txt Install Fails for gym

### ISSUE THREAD

**Issue by mattsthilaire** [huggingface/deep-rl-class#253]
When running the install for requirements.txt:

`!pip install -r https://raw.githubusercontent.com/huggingface/deep-rl-class/main/notebooks/unit1/requirements-unit1.txt`

The installs fail the same way described in this issue described in gym's repo: https://github.com/openai/gym/issues/3176

The suggested fix of doing `!pip3 install setuptools==65.5.0` works when using in colab. Suggest installing this version of setuptools in the requirements.txt.

**Comment by simoninithomas** [comment]
Thanks a lot for the fix 🤗 we merged it. I'm closing this issue then
