### ISSUE TITLE
Unit3: Training directly in colab without using local system

### ISSUE THREAD

**Issue by shivraj8615** [huggingface/deep-rl-class#254]
Hey as the training process takes lots of time in execution for 10M steps which can cause colab timing out. So the recommended way is to Download dqn.yml file from FILE > Downloads and to make change in dqn.yml n_timesteps: !!float 1e7 to !!float 1e6 and again upload to colab and remove original file from there. Any other way to do it.

**Comment by simoninithomas** [comment]
Hey there 👋 ,
I don't understand the issue? You have two solutions:
1. Do in colab
2. If you train on your computer you don't need to put it again on colab. You modify the config.yml and train on your computer using the ipynb file (Jupyter notebook)

**Comment by simoninithomas** [comment]
Closing the issue 🤗
