### ISSUE TITLE
Unit 1: Two main approaches for solving RL problems

### ISSUE THREAD

**Issue by BernardDhert** [huggingface/deep-rl-class#257]
![image](https://user-images.githubusercontent.com/91317422/227568718-9becd430-f2eb-4ff5-9e8a-a5f1412f66a2.png)

This picture has no white background so the text is not readable in dark mode. :)

**Comment by simoninithomas** [comment]
Oh thanks for pointing this out 🤗 I'm adding this the big Tuesday Update. I keep you updated

**Comment by BernardDhert** [comment]
Awesome!
