### ISSUE TITLE
Unit 7 - Self Play - Typo - TD-Gammon was 1995 not 1955

### ISSUE THREAD

**Issue by Rebolforces** [huggingface/deep-rl-class#258]
Wrong year in text.  TD-Gammon was 1995 not 1955. 
ref. 'Temporal difference learning and TD-Gammon' https://dl.acm.org/doi/10.1145/203330.203343

"The theory behind self-play is not something new. It was already used by Arthur Samuel’s checker player system in the fifties and by Gerald Tesauro’s TD-Gammon in 1955" should be 

"The theory behind self-play is not something new. It was already used by Arthur Samuel’s checker player system in the fifties and by Gerald Tesauro’s TD-Gammon in 1995"

**Comment by simoninithomas** [comment]
Hey there 👋 thanks for pointing this out. I'm adding it to the next update (Tuesday) but the date since to be 1992 ? https://en.wikipedia.org/wiki/TD-Gammon

**Comment by simoninithomas** [comment]
It's updated in the last merge. Thanks 🤗
