### ISSUE TITLE
Unit 6 - PandaReachDense 

### ISSUE THREAD

**Issue by felipeoliverai** [huggingface/deep-rl-class#259]
I'm facing this error: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp14cooz0z/-step-0-to-step-1000.mp4' 
after training the model and trying to push to the HF Hub.

**Comment by simoninithomas** [comment]
Hey there 👋 , I need more context:
- Did you trained on your computer or colab?
- Did you followed each step of the colab?

**Comment by felipeoliverai** [comment]
Hey @simoninithomas it was trained in my computer
