### ISSUE TITLE
Translation to Chinese 

### ISSUE THREAD

**Issue by Bob-AFei** [huggingface/deep-rl-class#26]
Hello there,  thanks for the course. 
The course is great, and I am sure that there are lots of Chinese students who want to study this course. 
Is there any plan to translate this course to Chinese?
If not, I think I can work on that. 

: )

**Comment by simoninithomas** [comment]
Hi,
It's not planned yet, we might in the future translate in different languages as we done with the Hugging Face NLP course. But if you're interested I can keep you in touch 🤗

**Comment by Bob-AFei** [comment]
Please don't hesitate to tell me, then.
