### ISSUE TITLE
Unit 3: Issue Installing Gym 

### ISSUE THREAD

**Issue by mattsthilaire** [huggingface/deep-rl-class#261]
Seems like Unit 3 suffers from the same issue installing gym we saw in issues #251 and #253.

Suggesting we add a cell to Unit 3's notebook `!pip3 install setuptools==65.5.0` right before the requirements.txt cell:

```
!pip install -r requirements.txt
# Since colab uses Python 3.9 we need to add this installation
!pip install gym[atari,accept-rom-license]==0.21.0
```

@simoninithomas I saw you were going to do a big update Tuesday. Did you want to add this to that update? If not I can make a quick PR for it on my end.

**Comment by simoninithomas** [comment]
Hey there, if you can make a PR I will merge it today 🤗 thanks
