### ISSUE TITLE
Unit 6: PandaReachDense observation space

### ISSUE THREAD

**Issue by helpingstar** [huggingface/deep-rl-class#264]
```python
import gym

env_id = "PandaReachDense-v2"

# Create the env
env = gym.make(env_id)

# Get the state space and action space
s_size = env.observation_space.shape
a_size = env.action_space

print("_____OBSERVATION SPACE_____ \n")
print("The State Space is: ", s_size)
print("Sample observation", env.observation_space.sample())  # Get a random observation
```
```
_____OBSERVATION SPACE_____ 

The State Space is:  None
Sample observation OrderedDict([('achieved_goal', array([4.3490624, 1.7946942, 5.433256 ], dtype=float32)), ('desired_goal', array([-9.161509 ,  4.8263154,  5.93399  ], dtype=float32)), ('observation', array([ 7.4350457, -8.889457 , -8.271049 , -7.112481 , -0.3806866,
       -8.340974 ], dtype=float32))])
```

In the code above in Unit6, `env.observation_space.shape` returns `None`. 

Since the observation_space of "PandaReachDense-v2" is a `Dict`, I think it would be better to do `s_size = env.observation_space` like `a_size = env.action_space` or specify a property like `s_size=env.observation_space['observation']`. 

However, `s_size = env.observation_space` looks more natural because the sample is obtained immediately like `env.observation_space.sample()` in the code behind.

**Comment by simoninithomas** [comment]
Hey there 👋 we currently updating this unit to work with Gymnasium I keep you updated.
