### ISSUE TITLE
Bonus Unit 3 -  Godot RL Agents: clarify instructions 

### ISSUE THREAD

**Issue by joelpaulkoch** [huggingface/deep-rl-class#265]
Hi thanks for making this course, it's really great.

The part about [Godot RL Agents](https://huggingface.co/deep-rl-course/unitbonus3/godotrl?fw=pt) is also nice to follow, until the point when I wanted to start training.
So, everything was clear to me until this sentence: 

> You can run training live in the the editor, but first launching the python training with `python examples/clean_rl_example.py —env-id=debug`

In the Godot environment there is no examples folder and there are no python scripts, so it was unclear to me where to go.
At the end, I cloned the [godot_rl_agents](https://github.com/edbeeching/godot_rl_agents) repository and found the python script there.
In my opinion, this could be clearer.

The second point is that "--env-id=debug" results in an unrecognized argument error, "--env_path=debug" works, and I could train my RingPong agents.

**Comment by simoninithomas** [comment]
Hey there, I tag @edbeeching who wrote the tutorial and library to check with you 🤗

**Comment by edbeeching** [comment]
@joelpaulkoch, thanks for the feedback. I have updated the instructions.

Let me know if you have further issues. I have recently revamped the docs in the [Godot RL Agents repo](https://github.com/edbeeching/godot_rl_agents) if you need more in depth examples / tutorials.
