### ISSUE TITLE
Unit 4: Hands-on 'FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb''

### ISSUE THREAD

**Issue by basboot** [huggingface/deep-rl-class#266]
Running cell 2 there was a problem with xvfb:

```FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'```

I was able to solve this by using the suggestion found here (https://www.tensorflow.org/agents/tutorials/9_c51_tutorial) to update apt in cell 1:

```%%capture
!sudo apt update
!apt install python-opengl
!apt install ffmpeg
!apt install xvfb
!pip install pyvirtualdisplay
!pip install pyglet==1.5.1
```

**Comment by simoninithomas** [comment]
Hey there 👋 I just tested the cell and it works. Did you turn on the GPU for notebook?

**Comment by simoninithomas** [comment]
Closing the issue for now (stale) don't hesitate to reopen it if you still have the problem 🤗
