### ISSUE TITLE
Should Gymnasium be Imported Insead of Gym?

### ISSUE THREAD

**Issue by Jpalmer95** [huggingface/deep-rl-class#274]
For use of gym in the Lunar Lander unit 1 Colab, should we be importing 'gymnasium' as 'gym' now instead of simply importing 'gym'?

First link: https://www.gymlibrary.dev/environments/box2d/lunar_lander/

Second link claiming that gymnasium is the newer version that is backwards compatible with gym. Popped up as a modal from the link within the Lunar Landing course.
https://gymnasium.farama.org/

**Comment by ricalanis** [comment]
I have the same curiosity, but since Colab has a gym built in, I wonder if we want to wait until it becomes part of the Colab env. Or, instead, install it and import it proactively.

**Comment by simoninithomas** [comment]
Hey there 👋 for the stability of the course we prefer to use Gym for now. We plan to make an update with gymnasium in the future.

**Comment by simoninithomas** [comment]
Hey there 👋 FIY we starting the update on using gymanasium instead of classical gym it was delayed due to priority tasks.

**Comment by simoninithomas** [comment]
Quick update:
✅  Unit 1
✅  Unit 2
- Unit 3
✅  Unit 4 (not updated because gym-games does not work with gymnasium)
- Unit 6 (updating only for panda-gym not pybullet)
✅  Unit 8 (not updated for now since the implementation works only with gym=0.21)

**Comment by simoninithomas** [comment]
Unit 3 is updated with Gymnasium there is still Unit 6 to update

**Comment by simoninithomas** [comment]
Unit 6 will be updated this week I'm closing this issue 🤗
