### ISSUE TITLE
Unit 3 : Higlighting rectangle hides part of the equation and can bring confusion

### ISSUE THREAD

**Issue by RubenGres** [huggingface/deep-rl-class#280]
In the unit3, the orange rectangles highlighting the part of the code for the Fixed Q-Target hides the circumflex on ^Q.
This can confuse people as Q (without the circumflex) is also used in the algortihm.

Here is the link to the image I am refering to:
https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit4/fixed-q-target-pseudocode.jpg

![fixed-q-target-pseudocode](https://user-images.githubusercontent.com/23587703/231217597-925ae423-b091-4bbb-a463-ec24a3b32e76.jpg)

**Comment by simoninithomas** [comment]
Thanks for pointing this out 🤗 I'm adding that to the next update #284

**Comment by simoninithomas** [comment]
Edit: I updated the illustration thanks again for pointing this out 🤗 I'm closing the issue
