### ISSUE TITLE
Unit 8 Part 2! Error:-Cannot build wheels for Vizdoom, issue in setup.py

### ISSUE THREAD

**Issue by tahsin12zaman** [huggingface/deep-rl-class#294]
The code is originally from Huggingface Deep RL Unit 8 Part 2, there seems to be an issue in the subprocess perhaps something the developers should look at! basically the error is:- Cannot build wheels for Vizdoom, issue in setup.py. 

(Note:- I tried many things to solve this issue, at one point I thought I've probably installed some unknown library/dependency by accident, so I decided to try on from scratch in a completely different laptop with different email/username in colab without editing the code one bit but I got the same error, but in my original laptop the first time i ran it, this piece of code had run without a hitch, with vizdoom getting installed)

More details given below:-

Full Error message running this piece of code for huggingface Deep RL Unit 8 Part 2:-

# install python libraries
# thanks toinsson
!pip install sample-factory==2.0.2
!pip install faster-fifo==1.4.2
!pip install vizdoom

The entire error message is as below:-
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting sample-factory==2.0.2
  Downloading sample_factory-2.0.2-py3-none-any.whl (9.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 86.1 MB/s eta 0:00:00
Collecting faster-fifo<2.0,>=1.4.2
  Downloading faster-fifo-1.4.5.tar.gz (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.0/87.0 kB 13.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyglet
  Downloading pyglet-2.0.5-py3-none-any.whl (831 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 831.3/831.3 kB 60.1 MB/s eta 0:00:00
Requirement already satisfied: tensorboard>=1.15.0 in /usr/local/lib/python3.9/dist-packages (from sample-factory==2.0.2) (2.12.2)
Requirement already satisfied: psutil>=5.7.0 in /usr/local/lib/python3.9/dist-packages (from sample-factory==2.0.2) (5.9.5)
Collecting colorlog
  Downloading colorlog-6.7.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.9/dist-packages (from sample-factory==2.0.2) (3.11.0)
Collecting signal-slot-mp<2.0,>=1.0.3
  Downloading signal_slot_mp-1.0.3-py3-none-any.whl (11 kB)
Collecting tensorboardx>=2.0
  Downloading tensorboardX-2.6-py2.py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 15.3 MB/s eta 0:00:00
Collecting torch<2.0,>=1.9
  Downloading torch-1.13.1-cp39-cp39-manylinux1_x86_64.whl (887.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.4/887.4 MB 1.8 MB/s eta 0:00:00
Collecting wandb>=0.12.9
  Downloading wandb-0.15.0-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 86.2 MB/s eta 0:00:00
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from sample-factory==2.0.2) (3.1.0)
Collecting gym<1.0,>=0.26.1
  Downloading gym-0.26.2.tar.gz (721 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 721.7/721.7 kB 63.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting huggingface-hub<1.0,>=0.10.0
  Downloading huggingface_hub-0.13.4-py3-none-any.whl (200 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.1/200.1 kB 26.0 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.18.1<2.0 in /usr/local/lib/python3.9/dist-packages (from sample-factory==2.0.2) (1.22.4)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.9/dist-packages (from sample-factory==2.0.2) (4.7.0.72)
Requirement already satisfied: cython>=0.29 in /usr/local/lib/python3.9/dist-packages (from faster-fifo<2.0,>=1.4.2->sample-factory==2.0.2) (0.29.34)
Requirement already satisfied: setuptools>=45.2.0 in /usr/local/lib/python3.9/dist-packages (from faster-fifo<2.0,>=1.4.2->sample-factory==2.0.2) (67.6.1)
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.9/dist-packages (from gym<1.0,>=0.26.1->sample-factory==2.0.2) (2.2.1)
Requirement already satisfied: importlib-metadata>=4.8.0 in /usr/local/lib/python3.9/dist-packages (from gym<1.0,>=0.26.1->sample-factory==2.0.2) (6.4.1)
Requirement already satisfied: gym-notices>=0.0.4 in /usr/local/lib/python3.9/dist-packages (from gym<1.0,>=0.26.1->sample-factory==2.0.2) (0.0.8)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub<1.0,>=0.10.0->sample-factory==2.0.2) (23.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub<1.0,>=0.10.0->sample-factory==2.0.2) (4.5.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from huggingface-hub<1.0,>=0.10.0->sample-factory==2.0.2) (2.27.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub<1.0,>=0.10.0->sample-factory==2.0.2) (4.65.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.9/dist-packages (from huggingface-hub<1.0,>=0.10.0->sample-factory==2.0.2) (6.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.9/dist-packages (from tensorboard>=1.15.0->sample-factory==2.0.2) (1.53.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.9/dist-packages (from tensorboard>=1.15.0->sample-factory==2.0.2) (0.7.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.9/dist-packages (from tensorboard>=1.15.0->sample-factory==2.0.2) (2.17.3)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.9/dist-packages (from tensorboard>=1.15.0->sample-factory==2.0.2) (0.40.0)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.9/dist-packages (from tensorboard>=1.15.0->sample-factory==2.0.2) (1.4.0)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in /usr/local/lib/python3.9/dist-packages (from tensorboard>=1.15.0->sample-factory==2.0.2) (1.0.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.9/dist-packages (from tensorboard>=1.15.0->sample-factory==2.0.2) (1.8.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.9/dist-packages (from tensorboard>=1.15.0->sample-factory==2.0.2) (3.4.3)
Requirement already satisfied: protobuf>=3.19.6 in /usr/local/lib/python3.9/dist-packages (from tensorboard>=1.15.0->sample-factory==2.0.2) (3.20.3)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from tensorboard>=1.15.0->sample-factory==2.0.2) (2.2.3)
Collecting nvidia-cublas-cu11==11.10.3.66
  Downloading nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 4.6 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu11==8.5.0.96
  Downloading nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (557.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 2.6 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu11==11.7.99
  Downloading nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 65.6 MB/s eta 0:00:00
Collecting nvidia-cuda-nvrtc-cu11==11.7.99
  Downloading nvidia_cuda_nvrtc_cu11-11.7.99-2-py3-none-manylinux1_x86_64.whl (21.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 68.9 MB/s eta 0:00:00
Collecting docker-pycreds>=0.4.0
  Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Collecting pathtools
  Downloading pathtools-0.1.2.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: appdirs>=1.4.3 in /usr/local/lib/python3.9/dist-packages (from wandb>=0.12.9->sample-factory==2.0.2) (1.4.4)
Collecting sentry-sdk>=1.0.0
  Downloading sentry_sdk-1.20.0-py2.py3-none-any.whl (198 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.8/198.8 kB 28.2 MB/s eta 0:00:00
Collecting setproctitle
  Downloading setproctitle-1.3.2-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30 kB)
Requirement already satisfied: Click!=8.0.0,>=7.0 in /usr/local/lib/python3.9/dist-packages (from wandb>=0.12.9->sample-factory==2.0.2) (8.1.3)
Collecting GitPython!=3.1.29,>=1.0.0
  Downloading GitPython-3.1.31-py3-none-any.whl (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 kB 26.4 MB/s eta 0:00:00
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.9/dist-packages (from docker-pycreds>=0.4.0->wandb>=0.12.9->sample-factory==2.0.2) (1.16.0)
Collecting gitdb<5,>=4.0.1
  Downloading gitdb-4.0.10-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 9.7 MB/s eta 0:00:00
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.9/dist-packages (from google-auth<3,>=1.6.3->tensorboard>=1.15.0->sample-factory==2.0.2) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.9/dist-packages (from google-auth<3,>=1.6.3->tensorboard>=1.15.0->sample-factory==2.0.2) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from google-auth<3,>=1.6.3->tensorboard>=1.15.0->sample-factory==2.0.2) (5.3.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.9/dist-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard>=1.15.0->sample-factory==2.0.2) (1.3.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.9/dist-packages (from importlib-metadata>=4.8.0->gym<1.0,>=0.26.1->sample-factory==2.0.2) (3.15.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface-hub<1.0,>=0.10.0->sample-factory==2.0.2) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface-hub<1.0,>=0.10.0->sample-factory==2.0.2) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface-hub<1.0,>=0.10.0->sample-factory==2.0.2) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->huggingface-hub<1.0,>=0.10.0->sample-factory==2.0.2) (1.26.15)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.9/dist-packages (from werkzeug>=1.0.1->tensorboard>=1.15.0->sample-factory==2.0.2) (2.1.2)
Collecting smmap<6,>=3.0.1
  Downloading smmap-5.0.0-py3-none-any.whl (24 kB)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.9/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=1.15.0->sample-factory==2.0.2) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.9/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard>=1.15.0->sample-factory==2.0.2) (3.2.2)
Building wheels for collected packages: faster-fifo, gym, pathtools
  Building wheel for faster-fifo (pyproject.toml) ... done
  Created wheel for faster-fifo: filename=faster_fifo-1.4.5-cp39-cp39-linux_x86_64.whl size=356657 sha256=ccb3de132617e5f61e121e7bd358832bc48739f8b456e2708bcadd8e67c67441
  Stored in directory: /root/.cache/pip/wheels/9f/2c/8f/2a67c7cefc7551a4dc9de521a298836583f9946b6b50d7e696
  Building wheel for gym (pyproject.toml) ... done
  Created wheel for gym: filename=gym-0.26.2-py3-none-any.whl size=827653 sha256=87a39e558b0426cdd265f0107ada1d6d69953f0f3c55c9fff3c92747b1aa5364
  Stored in directory: /root/.cache/pip/wheels/af/2b/30/5e78b8b9599f2a2286a582b8da80594f654bf0e18d825a4405
  Building wheel for pathtools (setup.py) ... done
  Created wheel for pathtools: filename=pathtools-0.1.2-py3-none-any.whl size=8807 sha256=d98d78d3810ff1ae74df5f02a3b9f1904d7a27b09452e009c36fd148ab07cc5d
  Stored in directory: /root/.cache/pip/wheels/b7/0a/67/ada2a22079218c75a88361c0782855cc72aebc4d18d0289d05
Successfully built faster-fifo gym pathtools
Installing collected packages: pyglet, pathtools, tensorboardx, smmap, setproctitle, sentry-sdk, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cublas-cu11, faster-fifo, docker-pycreds, colorlog, signal-slot-mp, nvidia-cudnn-cu11, huggingface-hub, gym, gitdb, torch, GitPython, wandb, sample-factory
  Attempting uninstall: gym
    Found existing installation: gym 0.25.2
    Uninstalling gym-0.25.2:
      Successfully uninstalled gym-0.25.2
  Attempting uninstall: torch
    Found existing installation: torch 2.0.0+cu118
    Uninstalling torch-2.0.0+cu118:
      Successfully uninstalled torch-2.0.0+cu118
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchtext 0.15.1 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchdata 0.6.0 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchaudio 2.0.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
dopamine-rl 4.0.6 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
Successfully installed GitPython-3.1.31 colorlog-6.7.0 docker-pycreds-0.4.0 faster-fifo-1.4.5 gitdb-4.0.10 gym-0.26.2 huggingface-hub-0.13.4 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 pathtools-0.1.2 pyglet-2.0.5 sample-factory-2.0.2 sentry-sdk-1.20.0 setproctitle-1.3.2 signal-slot-mp-1.0.3 smmap-5.0.0 tensorboardx-2.6 torch-1.13.1 wandb-0.15.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting faster-fifo==1.4.2
  Downloading faster-fifo-1.4.2.tar.gz (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.6/84.6 kB 10.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cython>=0.29 in /usr/local/lib/python3.9/dist-packages (from faster-fifo==1.4.2) (0.29.34)
Requirement already satisfied: setuptools>=45.2.0 in /usr/local/lib/python3.9/dist-packages (from faster-fifo==1.4.2) (67.6.1)
Building wheels for collected packages: faster-fifo
  Building wheel for faster-fifo (pyproject.toml) ... done
  Created wheel for faster-fifo: filename=faster_fifo-1.4.2-cp39-cp39-linux_x86_64.whl size=346504 sha256=c04e200411a2a431e46318231f3959a9dc7bf3821b8a5b36279e7a31b2ca124a
  Stored in directory: /root/.cache/pip/wheels/0c/6e/e5/093da430960f5d651cd6e13cb1fe7424ad422887c9ca0d376f
Successfully built faster-fifo
Installing collected packages: faster-fifo
  Attempting uninstall: faster-fifo
    Found existing installation: faster-fifo 1.4.5
    Uninstalling faster-fifo-1.4.5:
      Successfully uninstalled faster-fifo-1.4.5
Successfully installed faster-fifo-1.4.2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting vizdoom
  Downloading vizdoom-1.1.14.tar.gz (15.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 53.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from vizdoom) (1.22.4)
Building wheels for collected packages: vizdoom
  error: subprocess-exited-with-error
  
  × Building wheel for vizdoom (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for vizdoom (pyproject.toml) ... error
  ERROR: Failed building wheel for vizdoom
Failed to build vizdoom
ERROR: Could not build wheels for vizdoom, which is required to install pyproject.toml-based projects

**Comment by sw32-seo** [comment]
I solved the problem by executing the below two lines before any dependency installation.
Then I removed the last ```pip install vizdoom```. 

```
!apt-get install cmake git libboost-all-dev libsdl2-dev libopenal-dev
!pip install vizdoom
```

This is the original installation guide from vizdoom repo ([link](https://github.com/Farama-Foundation/ViZDoom#apt-based-distros-ubuntu-debian-linux-mint-etc))

I hope this could help you too.

**Comment by tahsin12zaman** [comment]
so did you do it in linux or windows?

**Comment by simoninithomas** [comment]
Hey there I just tested the notebook and I don't have the error did you run it on colab or it was on your machine?

**Comment by sw32-seo** [comment]
The error occurs on colab.

**Comment by simoninithomas** [comment]
I don't see the issue anymore I'm closing it for now. Don't hesitate to open it again if you encounter this issue again 🤗
