### ISSUE TITLE
package_to_hub causing error

### ISSUE THREAD

**Issue by SandeepaDevin** [huggingface/deep-rl-class#298]
I have executed the colab notebook code but in kaggle (for more GPU resources), and I couldn't use package_to_hub in it. Everything else upto that point worked well.

It causes the error

/opt/conda/lib/python3.7/site-packages/pyglet/gl/__init__.py in <module>
    233 elif compat_platform == 'darwin':
    234     from .cocoa import CocoaConfig as Config
--> 235 del base  # noqa: F821
    236 
    237 

NameError: name 'base' is not defined

I couldn't figure out any way to make this work

**Comment by simoninithomas** [comment]
Did you created a virtualenv? Most of the time this error is because the virtualenv was not created or it had a bug
