### ISSUE TITLE
Problems with importing pkgs DeepRL Unit 1 Hands-on

### ISSUE THREAD

**Issue by vivchc** [huggingface/deep-rl-class#302]
Nearly every line from the code block below gives me an error:
```
import gym

from huggingface_sb3 import load_from_hub, package_to_hub, push_to_hub
from huggingface_hub import notebook_login # To log to our Hugging Face account to be able to upload models to the Hub.

from stable_baselines3 import PPO
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_vec_env
```

I tried installing the packages separately, but it still gives me the errors:
```
!pip install huggingface-sb3==0.5
!pip install stable-baselines3
```

The exact errors I get:

- cannot import name 'package_to_hub' from 'huggingface_sb3'
- No module named 'stable_baselines3' (for all stable_baselines3 imports)

Things that are fine:
- I can import `load_from_hub, push_to_hub` from huggingface_sb3 
- Found the solution to `from huggingface_hub import notebook_login` by adding `notebook_login()` right after

**Comment by simoninithomas** [comment]
Hey there 👋 we are updating the course and we just updated this Unit, we didn't merged it yet but here's the new notebook that works with gymnasium: https://github.com/huggingface/deep-rl-class/blob/GymnasiumUpdate/Unit1/notebooks/unit1/unit1.ipynb

**Comment by simoninithomas** [comment]
Edit we updated it should work correctly now 🤗
