### ISSUE TITLE
Unit 7 : Impossibe to install the aivsai brancch of the ml-agents repo (no issues can be opened there)

### ISSUE THREAD

**Issue by Victorivus** [huggingface/deep-rl-class#306]
For unit 7, the reopo https://github.com/huggingface/ml-agents doeoes not accept issues.

Installation failed with: 
`"TypeError: Descriptors cannot not be created directly."`

I could solve it by changing `protobuf` version:

`pip install protobuf==3.20.3`

After that, training failed because there was no `onnx` installed so:

`pip install onnx`

and then it got going (:

P.S: sorry if this is not the way of doing this/communicating these problems, willing to learn how to do it if someone explains.

**Comment by simoninithomas** [comment]
No problem.

So let's try to see why it does not work

What's your OS?

**Comment by Wintoplay** [comment]
Try to control torch to be 1.8
