### ISSUE TITLE
Unit 1: Error while pushing code to hub ('DummyVecEnv' object has no attribute 'render_mode')

### ISSUE THREAD

**Issue by krvicky** [huggingface/deep-rl-class#308]
While running the following block of code, I am getting the error 'DummyVecEnv' object has no attribute 'render_mode' as shown in the screenshot and the model is not pushed to the hub.  I checked in Discord and there are more users facing this issue

````
import gym
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.env_util import make_vec_env

from huggingface_sb3 import package_to_hub
repo_id = "Neomedallion/ppo-LunarLander-v2"
env_id = "LunarLander-v2"
eval_env = make_vec_env("LunarLander-v2", n_envs=1)
model_architecture = "PPO"
commit_message = "Push LunarLander-v2 model as part of HF Unit 1"

package_to_hub(model=model, # Our trained model
               model_name=model_name, # The name of our trained model 
               model_architecture=model_architecture, # The model architecture we used: in our case PPO
               env_id=env_id, # Name of the environment
               eval_env=eval_env, # Evaluation Environment
               repo_id=repo_id, 
               commit_message=commit_message)
````
![image](https://user-images.githubusercontent.com/48130492/235816179-d8b3720b-eb2f-48e6-a6c3-f042edd6d8a1.png)

**Comment by simoninithomas** [comment]
Hey there 👋 sorry for this bug, we are updating the notebook with gymnasium (new version of gym) hopefully with it you'll not have these kind of bugs, you can find the new version here: https://github.com/huggingface/deep-rl-class/blob/GymnasiumUpdate/Unit1/notebooks/unit1/unit1.ipynb

I'm going to merge tonight but you can access it already.

**Comment by simoninithomas** [comment]
Edit: We merged it I'm closing this issue 🤗
