### ISSUE TITLE
Add knowledge checks

### ISSUE THREAD

**Issue by osanseviero** [huggingface/deep-rl-class#31]
It would be cool to have some knowledge checks at the end of each unit

**Comment by simoninithomas** [comment]
Added to my list 📝

**Comment by osanseviero** [comment]
Re-opening until it's merged if that's ok so we don't lose track :smile:

**Comment by simoninithomas** [comment]
I've made one for the first Unit: https://github.com/huggingface/deep-rl-class/blob/main/unit1/quiz.md#knowledge-check-%EF%B8%8F

**Comment by osanseviero** [comment]
Closing now as there are quizzes for both units 1 and 2! :fire:
