### ISSUE TITLE
unit 4 hands-on PixelCopter action space

### ISSUE THREAD

**Issue by joeADSP** [huggingface/deep-rl-class#315]
In unit 4 hands-on PixelCopter exercise notes https://github.com/huggingface/deep-rl-class/blob/main/units/en/unit4/hands-on.mdx

action space is given as [up, down]

```
The action space(2) 🎮:
- Up
- Down
```

Per the PixelCopter docs https://pygame-learning-environment.readthedocs.io/en/latest/user/games/pixelcopter.html, the only movement action is `up` (active pressing of the accelerator).

Should the second action in the action space be described as `do nothing / no action` i.e. the absence of pressing the accelerator rather than `down`?

**Comment by simoninithomas** [comment]
Indeed that's a mistake thanks for pointing out 🤗 . Do you want to open a PR to update it?
