### ISSUE TITLE
Failing Models halt execution of the SoccerTwos leaderboard

### ISSUE THREAD

**Issue by dfm794** [huggingface/deep-rl-class#320]
# Describe the bug

Per Thomas Simonini, when uploaded models fail to execute properly and break the exe for the game, the match playing algorithm won't proceed to the next match. The leaderboard then fails to execute until a manual search for the model and it's deletion takes place

# Material

 - Did you use Google Colab?
This is not relevant, this is a hugging face repo running in a hugging face space

If not:
 - Your Operating system (OS)
 - Version of your OS
See Above

Per a thread on the discord #ai-vs-ai-challenge, wrapping the matches in a try/catch block to enable recovery, skipping the offending match.

**Comment by simoninithomas** [comment]
Thanks for the info this is something I'm working on this week to solve the issue. I keep you updated 🤗

**Comment by simoninithomas** [comment]
Hey there 👋 , to keep you updated we still experience some bugs but I'm relaunching the machine to test the new updates. Don't hesitate to check this week if your scores are displayed if not please tell me in this issue 🤗
