### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by DiogenesBR** [huggingface/deep-rl-class#324]
Can I start translating this course to Portuguese?

I'm not a professional translator, not even concluded the course, but with a AI tool I think I can do a good job. 😀
Also can use the translation as a mean to better understand the concepts.

Best Regards

**Comment by simoninithomas** [comment]
Hey there 👋 we don't plan for now to make official course translation but we might do it in the future. I'm keeping your name to contact you if and when we will do it 🤗
