### ISSUE TITLE
[HANDS-ON BUG]

### ISSUE THREAD

**Issue by Yasser-Cloud** [huggingface/deep-rl-class#326]
# AttributeError: 'DummyVecEnv' object has no attribute 'recording'

I get a lot of problems with the unit3 hands-on from the installations stable-baselines3 and gym  libraries solved it and trained the RL model but can't record video for the Atari game provided link below 
**[Please share your notebook link so that we can reproduce the error](https://colab.research.google.com/drive/1Fjebu14Hav6w1OLSpryLg2uzdQEbivcv?usp=sharing)**

# Material

 - Did you use Google Colab? Yes

**Comment by simoninithomas** [comment]
Hey there 👋 this issue comes from the new gymnasium system. We currently working on this week on finishing the new package_to_hub that solves this issue I keep you updated 🤗

**Comment by Yasser-Cloud** [comment]
Thank you 🤗

**Comment by simoninithomas** [comment]
The new notebook:  https://colab.research.google.com/github/huggingface/deep-rl-class/blob/main/notebooks/unit3.ipynb

🤗
