### ISSUE TITLE
[Contributions welcome] Add example showing how to load a pretrained agent

### ISSUE THREAD

**Issue by osanseviero** [huggingface/deep-rl-class#33]
For Unit 1, there is no example showing how to load an agent from the hub. Having an example for it would be very very cool :fire:

**Comment by ironbar** [comment]
This should work

```
from huggingface_sb3 import load_from_hub
from stable_baselines3 import PPO

checkpoint = load_from_hub('utkusaglm/ppo-lunarlander-v4', 'ppo-LunarLander-v2.zip')
model = PPO.load(checkpoint)
```

**Comment by osanseviero** [comment]
Yes, maybe we could add this to the end of the notebook for unit 1

**Comment by simoninithomas** [comment]
Thanks for the help @ironbar I added your example to the unit 1 notebook update and mentionned you in the notebook 🤗
