### ISSUE TITLE
Google Colab Pro+

### ISSUE THREAD

**Issue by poornimag238** [huggingface/deep-rl-class#330]
As I am trying to run the week3 notebook after buying 100 compute units in colab, it is not completing the training the model.

Is it necessary to updat ethe Pro+.

**Comment by simoninithomas** [comment]
Hey there 👋 the Unit 3 has some bugs it will be solved this week. And no you don't need Colab Pro I used simple colab to train mine 🤗

**Comment by poornimag238** [comment]
Thank you for your timely reply.

**Comment by simoninithomas** [comment]
The new notebook:  https://colab.research.google.com/github/huggingface/deep-rl-class/blob/main/notebooks/unit3.ipynb

Have fun 🤗

**Comment by poornimag238** [comment]
Dear Thomas,
Happy evening,

When I run the notebook which is mentioned in the above mail, getting an
error w.r t. to dqn.yml

[image: image.png]

**Comment by poornimag238** [comment]
Yes, I did.
But still I am not able to run.

**Comment by simoninithomas** [comment]
Ok we updated the colab so normally it should work correctly. What you need to do is to open the new one: https://colab.research.google.com/github/huggingface/deep-rl-class/blob/main/notebooks/unit3/unit3.ipynb

**Comment by simoninithomas** [comment]
The requirements? You just need a free account in Google Colab and 1M training timesteps is good enough to get nice results. If you want to train more there's a risk of timeout.

**Comment by poornimag238** [comment]
Happy day sir,

I am still not able to run the sheet of Week3.

**Comment by simoninithomas** [comment]
Hey there 👋 , can you be more specific on why you can't run the new colab?

Did you tried the new version?: https://colab.research.google.com/github/huggingface/deep-rl-class/blob/main/notebooks/unit3/unit3.ipynb
