### ISSUE TITLE
Unit 1 Stochastic policy-based method recap graphic shows incorrect game image

### ISSUE THREAD

**Issue by padamson** [huggingface/deep-rl-class#331]
# Unit 1 Stochastic policy-based method recap graphic should show Mario game image, not simple unicorn game image

The Mario game image is used to illustrate an output probability distribution for a stochastic policy, but the recap graphic shows the unicorn game image. Replace the unicorn game image with the Mario game image in the Policy-Based Method Stochastic output recap graphic.

**Comment by simoninithomas** [comment]
Hey there 👋 thanks for the issue. I'm adding it to the next big update (next week) todo list🤗

**Comment by simoninithomas** [comment]
Thanks we updated the illustration 🤗
