### ISSUE TITLE
Clarify Monte Carlo Gt calculation in Unit 2

### ISSUE THREAD

**Issue by padamson** [huggingface/deep-rl-class#333]
# Clarify Gt calculation in description of Monte Carlo approach

In the description of the Gt calculation for the Monte Carlo approach, the equation for Gt is repeated, and the LHS of the equation should be G0 once the values for R1, R2... are substituted. Also, the formatting would look nicer if the equations weren't bulleted.

**Comment by simoninithomas** [comment]
Hey there 👋 thanks for the issue. I'm adding it to the next big update (next week) todo list🤗

**Comment by simoninithomas** [comment]
Thanks I merged your PR 🤗
