### ISSUE TITLE
Advantages/disadvantages between monte carlo and td learning

### ISSUE THREAD

**Issue by ironbar** [huggingface/deep-rl-class#34]
I have just read the part 1 of the introduction of Q-learning and althought I believe the methods are very well described I have missed an explanation of the advantages/disadvantages of using either methods. Maybe that will come in part 2 but just in case...

This [link](https://stats.stackexchange.com/questions/355820/why-do-temporal-difference-td-methods-have-lower-variance-than-monte-carlo-met) might be a good reference to explain the difference in variance and bias between the methods. 

This other [link](https://stats.stackexchange.com/questions/336974/when-are-monte-carlo-methods-preferred-over-temporal-difference-ones) also is very interesting regarding when it may have sense to use monte carlo over td.

Thanks and congratulations for the course
Guillermo

**Comment by simoninithomas** [comment]
Hi @ironbar, thanks for the feedback and the link 🤗 .
Indeed I didn't included the bias/variance tradeoff in this Unit, we want to dive deeper on this topic on Actor Critic Methods Unit but I think it's a good idea to add the two links in the reading list of this Unit 2. I'm doing the update.

Have a nice day,
