### ISSUE TITLE
Typo in Unit 1 Hands-on page

### ISSUE THREAD

**Issue by lordWalnuts** [huggingface/deep-rl-class#340]
Under the _**"Create the LunarLander environment 🌛 and understand how it works"**_ section, the link to the environment documentation is still in markdown

`[The environment 🎮](https://gymnasium.farama.org/environments/box2d/lunar_lander/)`

**Comment by simoninithomas** [comment]
Thanks I'm adding it to the update of the week 🤗

**Comment by simoninithomas** [comment]
Updated. Thanks again 🤗
