### ISSUE TITLE
[WEEK5]push the model to the hugging face

### ISSUE THREAD

**Issue by poornimag238** [huggingface/deep-rl-class#341]
1. !mlagents-push-to-hf  --run-id= "SnowballTarget3"  --local-dir= "./results/SnowballTarget3"  --repo-id= "Varaprabha/ppo-SnowballTargetTESTCOLAB"  --commit-message= "First Push".
2. When I used the above command to push the model I have encountered the following [error]

![image](https://github.com/huggingface/deep-rl-class/assets/47310924/e0ed89dc-52bf-4e51-a3ba-648eb40eab92)
![WEEK5_ERROR](https://github.com/huggingface/deep-rl-class/assets/47310924/b1bca837-acfa-44f3-9152-dfaf88eb954f)

**Comment by simoninithomas** [comment]
Can you try without the spaces between = and ""?
