### ISSUE TITLE
[UPDATE] Unit 1, sampling from observation space

### ISSUE THREAD

**Issue by dfomin** [huggingface/deep-rl-class#349]
The observation space is 8 float numbers but we know from the documentation that the last 2 numbers are actually boolean so they can be only 0 or 1. In a line
`print("Sample observation", env.observation_space.sample()) # Get a random observation`
we have 8 random floats including the last 2 of them and I found it a bit misleading since we can never get this observation from the environment. Maybe some additional clarification is needed here.

**Comment by simoninithomas** [comment]
Hey there 👋 thanks for pointing this out. I'm adding it to the next update list (August Update)

**Comment by simoninithomas** [comment]
Hey there 👋 thanks I updated the notebook and the hands-on.mdx 🤗
