### ISSUE TITLE
Week 7 not able to upload the model.

### ISSUE THREAD

**Issue by poornimag238** [huggingface/deep-rl-class#350]
![WEEK7_ERROR](https://github.com/huggingface/deep-rl-class/assets/47310924/0b7cc841-adb8-43e1-99f4-85a54766eae9)

I need help in correcting this error which occurred during uploading the model.

**Comment by poornimag238** [comment]
please suggest the way to correct this....

**Comment by simoninithomas** [comment]
Hey there 👋  I think you forget to put ! in front of mlagents. When you run bash command in Colab you need to add a !

So !mlagents-push-to-hf
