### ISSUE TITLE
[UPDATE] Innacurrate variable name random_int in unit2

### ISSUE THREAD

**Issue by andywalner** [huggingface/deep-rl-class#353]
# What do you want to improve?

- Explain the typo/error or the part of the course you want to improve

`random_int = random.uniform(0,1)` --> the variable should be called random_float

- **Also, don't hesitate to open a Pull Request with the update**.

**Comment by andywalner** [comment]
PR: https://github.com/huggingface/deep-rl-class/pull/354

**Comment by simoninithomas** [comment]
Thanks merged with #354
