### ISSUE TITLE
Unit#6: AttributeError: module 'gym' has no attribute 'GoalEnv'

### ISSUE THREAD

**Issue by ywigelman** [huggingface/deep-rl-class#355]
Hey, it seems I'm getting the following error while trying to make PandaReachDense-v2 environment with gym:

`AttributeError: module 'gym' has no attribute 'GoalEnv'
`

**snapshot:**
![image](https://github.com/huggingface/deep-rl-class/assets/46452128/360c2c43-6f97-4724-91b0-e31e949ee669)

a link to my [notebook](https://colab.research.google.com/drive/1Fx6yzYwCxTClXRohEdmMC63DCYNheUh_?usp=sharing)

 I am using Google Colab
 
thanks in advance for your assistance

**Comment by simoninithomas** [comment]
Hey there 👋 thanks for pointing this out. We currently updating the notebook I keep you updated 🤗

**Comment by drbeane** [comment]
I am having the same issue. Is there any update on this?
