### ISSUE TITLE
[HANDS-ON BUG] Unit#6 NameNotFound: Environment 'AntBulletEnv' doesn't exist.

### ISSUE THREAD

**Issue by ShridiptaSatpati** [huggingface/deep-rl-class#357]
Hey, it seems I'm getting the following error while trying execute the function make_vec_env with env_id="AntBulletEnv-v0" environment:

`NameNotFound: Environment 'AntBulletEnv' doesn't exist. `

but gym creates the "AntBulletEnv-v0" in one of the previous cells of the Unit 6 notebook without any problem.

**snapshot:**
![Screenshot (203)](https://github.com/huggingface/deep-rl-class/assets/62655063/a302afe3-c13b-4b51-abfc-3107de7a27a5)

I am using Google Colab

thanks in advance for your assistance

**Comment by arminmrm** [comment]
Hi! I exactly experienced this issue. I was able to fix it as follows:
`env = make_vec_env(lambda: gym.make(env_id), n_envs=4)`

**Comment by ShridiptaSatpati** [comment]
The training process executed without any hindrance after modifying according to your suggested changes but encountering the error `AssertionError: The render_mode must be 'rgb_array', not None` while pushing the trained agent to the hub.

![image](https://github.com/huggingface/deep-rl-class/assets/129827573/0658e767-1716-45a5-9d87-49a5d15ab9c8)

**Comment by arminmrm** [comment]
Yes, I exactly encountered the same issue, as well. I opened an [issue](https://github.com/huggingface/deep-rl-class/issues/358) for it and waiting for a response.

**Comment by arminmrm** [comment]
Hey @ShridiptaSatpati! Did you figure this out?

**Comment by ShridiptaSatpati** [comment]
@arminmrm Unfortunately I could not fix the problem. But Thomas Simonini and his team promised that they are still updating the Unit 6 notebook and they would be notifying us when it is ready. 

![image](https://github.com/huggingface/deep-rl-class/assets/129827573/df5c5752-db06-492f-b50a-099afe33ccf3)

You can join the discord server to receive the latest updates.
https://huggingface.co/learn/deep-rl-course/unit0/discord101?fw=pt has that discord link.

**Comment by MattBoraske** [comment]
+1 for encountering this issue as well.

**Comment by taleslimaf** [comment]
+1 for encountering this issue as well.

**Comment by MateoCamara** [comment]
+1 for encountering this issue as well.

**Comment by dummy-round** [comment]
Hi @ShridiptaSatpati, I think the problem is from the Stable-baselines3 new release: https://github.com/DLR-RM/stable-baselines3/releases/tag/v2.0.0 and they switch to Gymnasium for the backend, and Gymnasium seems not support the AntBulletEnv. So workaround is to try to install an older release of stable-baselines3. I added a line in the Colab: !pip install stable-baselines3[extra]==1.8.0 and it seems worked.
