### ISSUE TITLE
[HANDS-ON BUG] Unit 6: Issue with push_to_hub

### ISSUE THREAD

**Issue by arminmrm** [huggingface/deep-rl-class#358]
In Unit 6, I trained and evaluated the A2C model for the AntBulletEnv and everything looked good. However, when I try to push my model to the hub I get the following error: `AssertionError: The render_mode must be 'rgb_array', not None`

Here is the [link](https://colab.research.google.com/drive/12DaDBoahjVNjMbDTNlm0GxAVjT_xIbdC#scrollTo=ueuzWVCUTkfS) for my notebook. I appreciate it if you could help.

**Comment by taleslimaf** [comment]
Same problem here! =/

**Comment by Arindam75** [comment]
+1

**Comment by imzhangxian** [comment]
Experienced the same issue, but I can work it around by add a line of code before push_to_hub:
eval_env.render_mode='rgb_array'

Hope it help.
