### ISSUE TITLE
Unit 2: bug in evaluate_agent function

### ISSUE THREAD

**Issue by unfinity-core** [huggingface/deep-rl-class#37]
`episode_rewards` dosen't append `total_rewards_ep` if episode stops after 99 steps (for ex., when the agent performs useless cyclic actions). It leads to wrong evaluate scores on the Taxi-v3 leaderboard.

To fix it just add `episode_rewards.append(total_rewards_ep)` after inner loop (line 29).

UPD: i'm wrong. To fix it, move `episode_rewards.append(total_rewards_ep)` (from `if done:`) out of the inner loop like I did in the PR.

**Comment by osanseviero** [comment]
Thanks, good catch! Would you like to open a PR to fix this?

**Comment by unfinity-core** [comment]
I've created PR

**Comment by osanseviero** [comment]
Thanks for the fix! :hugs:
