### ISSUE TITLE
[UPDATE] Suggestion to improve instruction clarity in bonus-unit1

### ISSUE THREAD

**Issue by xitxat** [huggingface/deep-rl-class#375]
In Create the Huggy config file cell from bonus-unit1.ipynb, for first time users of notebooks and colab, it is not obvious how to create a file or how to "Go to /content/ml-agents/config/ppo".
I suggest adding "Click file icon on left sidebar of notebook."

@simoninithomas

**Comment by simoninithomas** [comment]
Good Idea I'm updating the notebook 🤗

**Comment by simoninithomas** [comment]
Merged thanks again 🤗
