### ISSUE TITLE
[UPDATE] Missing element from "Inside the Learning Component"

### ISSUE THREAD

**Issue by Sookeyy-12** [huggingface/deep-rl-class#376]
# Missing element from "Inside the Learning Component"
- It says that there are three important elements but only two elements are given.
- <img width="504" alt="image" src="https://github.com/huggingface/deep-rl-class/assets/82956207/81ee9467-689a-4415-afa7-42580d052825">

**Comment by simoninithomas** [comment]
Hey there 👋 , thanks for pointing this out 🤗 . The policy can be count as third element. But given it's part of the agent component I decided to change to 2 elements. I'll close the issue when I merge for the PR

https://github.com/huggingface/deep-rl-class/pull/379
