### ISSUE TITLE
[HANDS-ON BUG] Heading is not displayed correctly in Unit2.

### ISSUE THREAD

**Issue by Geson-anko** [huggingface/deep-rl-class#387]
# Describe the bug

This is a very minor error, but the heading is not shown correctly because there is no *space* after `##` in the heading of unit2 `##Define the epsilon-greedy policy 🤖`

# Material

- Google Chrome 115.0.5790.170（Official Build）unknown (64 bit)
![Screenshot from 2023-08-17 13-39-05](https://github.com/huggingface/deep-rl-class/assets/59220704/6a7c869d-3844-4e78-9b10-2e6040dcd792)

- https://huggingface.co/learn/deep-rl-course/unit2/hands-on

**Comment by simoninithomas** [comment]
Thanks for pointing this out 🤗 I solved it here #388
