### ISSUE TITLE
[UPDATE] Unit2 Q-tables typo

### ISSUE THREAD

**Issue by PierreCounathe** [huggingface/deep-rl-class#391]
# Typos in the (learned) Q-tables

- I think there is a typo in both images of the learned Q-tables in pages _Introducing Q-Learning_ and _Q-Learning Recap_ of the Unit 2 of the course. On the fourth line of the table, the -10 coefficient should appear in the second column (take a step to the right). I thought this might be confusing to people who pay attention to tables more than text.
- The typo also appears in the notebook as the same file is used.
- Cf below for the screenshots that show both the game setup and the learned Q-tables.
- I could not open a PR as I could not access the hosted image files.

## Screenshots
- Game setup
![Screenshot 2023-08-26 at 6 42 17 PM](https://github.com/huggingface/deep-rl-class/assets/72037857/1f43fdb0-93b3-430c-b081-548ef27657e2)
- [Introducing Q-Learning page] Typo in the right Q-table
- [Link to code line](https://github.com/huggingface/deep-rl-class/blob/1ed8d39ea764d576073c95af3a2617575c82b188/units/en/unit2/q-learning.mdx#L57C1-L58C1) 
![Screenshot 2023-08-26 at 6 43 00 PM](https://github.com/huggingface/deep-rl-class/assets/72037857/bfec8e89-e250-44db-b2ab-0c2f6d575135)
- [Q-Learning Recap] Typo in the right Q-table
- [Link to the code line](https://github.com/huggingface/deep-rl-class/blob/1ed8d39ea764d576073c95af3a2617575c82b188/units/en/unit2/q-learning-recap.mdx#L21)
![Screenshot 2023-08-26 at 6 43 39 PM](https://github.com/huggingface/deep-rl-class/assets/72037857/c450f0c9-9c6c-4088-92d2-84fc0186bc97)
- [Hands-on]
- [Link to code line](https://github.com/huggingface/deep-rl-class/blob/1ed8d39ea764d576073c95af3a2617575c82b188/notebooks/unit2/unit2.ipynb#L150C21-L150C49)

**Comment by simoninithomas** [comment]
Hey there 👋 thanks for pointing this out. Indeed there's an error. I'm updating the illustration

**Comment by simoninithomas** [comment]
Updated ✅

**Comment by PierreCounathe** [comment]
Hi @simoninithomas, thanks for the update!

I should have mentioned this, but there are two files used by the `.mdx` files.
`q-learning.mdx` uses this (second) file: https://huggingface.co/datasets/huggingface-deep-rl-course/course-images/resolve/main/en/unit3/Q-learning-1.jpg, that was not updated I think.

**Comment by simoninithomas** [comment]
I see thanks for pointing this out I update it 🤗
