### ISSUE TITLE
[UPDATE] Hands-on Unit 7

### ISSUE THREAD

**Issue by zhulinchng** [huggingface/deep-rl-class#396]
# What do you want to improve?

Unit 7 Hands-on need to add `pip install onnx==1.12.0` as part of the setup.

- Explain the typo/error or the part of the course you want to improve

```
Error: Module onnx is not installed
```

# Material
Google Colab is not used, instead Windows 11 22621.2215 is used.

[onnx v1.12.0](https://github.com/onnx/onnx/blob/v1.12.0/requirements.txt) is needed because of protobuf v3.19.6 is used for the setup, later versions of onnx is not compatible.

**Comment by zhulinchng** [comment]
PR at #398

**Comment by simoninithomas** [comment]
Thanks for the PR I merge it. I close the issue 🤗
