### ISSUE TITLE
leaderboard: metrics don't update after pushing changes to model

### ISSUE THREAD

**Issue by VitamintK** [huggingface/deep-rl-class#40]
[leaderboard](https://huggingface.co/spaces/chrisjay/Deep-Reinforcement-Learning-Leaderboard) doesn't appear to update scores when pushing changes to an existing model. I'm guessing this is due to [line 105 in app.py](https://huggingface.co/spaces/chrisjay/Deep-Reinforcement-Learning-Leaderboard/blob/main/app.py#L105), and should be changed to allow score updates.

**Comment by osanseviero** [comment]
Hey there! Now you can open PRs on the Hub! Would you be interested in submitting a fix for it?

**Comment by osanseviero** [comment]
@chrisemezue might be able to provide more context here :smile:

**Comment by chrisemezue** [comment]
> I don't think I have suitable context around why line 105 is the way it is. Will it cause any problems to change it to `model_ids = [x for x in get_model_ids(rl_env)]`?

thank you for bringing this up, and sorry about the inconvenience. I added the extra constraint in line 105 to save inference time by preventing re-loading previous model metadata. I will work on it now to make sure it takes pushes to existing models into consideration.
