### ISSUE TITLE
[HANDS-ON BUG] Unit-1: make sure model_name is not empty

### ISSUE THREAD

**Issue by znacer** [huggingface/deep-rl-class#402]
# Describe the bug

This bug is found in the following notebook : [Unit-1](https://colab.research.google.com/github/huggingface/deep-rl-class/blob/master/notebooks/unit1/unit1.ipynb#scrollTo=qKnYkNiVp89p)  
In section `Train the PPO agent 🏃` , an empty string is assigned by default to variable `model_name`.  
If one let this value to empty, an error will be raised in section `Load a saved LunarLander model from the Hub 🤗`. When user try to upload his model with an empty `model_name`.  
Error raised: `FileNotFoundError: [Errno 2] No such file or directory`

# Material

Google Colab

# Suggestions
Change 
```python
# TODO: Specify file name for model and save the model to file
model_name = ""
``` 
by 
```python
# TODO: Specify file name for model and save the model to file
model_name = "ppo-LunarLander-v2"
```
or  
```python
# TODO: Specify a non empty file name for model and save the model to file
model_name = 
```

**Comment by simoninithomas** [comment]
Hey, thanks for pointing this out 🤗. I'm adding it to this month update

**Comment by simoninithomas** [comment]
Updated thanks again 🤗
