### ISSUE TITLE
[HANDS-ON BUG]

### ISSUE THREAD

**Issue by tylerkiser** [huggingface/deep-rl-class#405]
# Describe the bug
![image](https://github.com/huggingface/deep-rl-class/assets/82686976/dbd1b49c-a54e-4149-b8c1-8e69daef14aa)

**Please share your notebook link so that we can reproduce the error**
I cannot push my code for this model because it says I am not connected to the physic server.  I ran the code in the precise order in the notebook.  Please help,  I have wasted compute multiple times.  
# Material

 - Did you use Google Colab?
yes
If not:
 - Your Operating system (OS)
 
 - Version of your OS

**Comment by tylerkiser** [comment]
Looks like it is running okay now, not sure why.

**Comment by simoninithomas** [comment]
Thanks for the update, sometimes we have some problems with colab and rl environments. For now we don't have a long term solution except restart the notebook
