### ISSUE TITLE
[UPDATE] ALL MATHS ARE NOT DISPLAYED

### ISSUE THREAD

**Issue by UniverseFly** [huggingface/deep-rl-class#407]
Hi there, it seems that all the mathematical formulas or symbols in the text are missing in the current version of the course. For example, in [Unit 8](https://huggingface.co/learn/deep-rl-course/unit8/clipped-surrogate-objective), there is an inconsistent paragraph:

<img width="670" alt="image" src="https://github.com/huggingface/deep-rl-class/assets/46997596/8c3a5f46-f711-4303-8585-8e9aed2c1cdd">

I noticed that the source file introduced some maths that failed to be displayed:

```
As we can see, \\( r_t(\theta) \\) denotes the probability ratio between the current and old policy:

- If \\( r_t(\theta) > 1 \\), the **action \\( a_t \\) at state \\( s_t \\) is more likely in the current policy than the old policy.**
- If \\( r_t(\theta) \\) is between 0 and 1, the **action is less likely for the current policy than for the old one**.
```

This error also exists in other units, such as the [proof of policy gradient](https://huggingface.co/learn/deep-rl-course/unit4/pg-theorem) where all equations disappeared.

**Comment by simoninithomas** [comment]
Hey there 👋 thanks for pointing this out indeed it seems there's a bug with doc-builder we're investigating why. Sorry for the inconvenience. In the meantime the best is to read with mdx.

**Comment by simoninithomas** [comment]
The problem has been solved thanks for pointing this out 🤗
