### ISSUE TITLE
Unit 7: Self Play. Ommission of rating in example 

### ISSUE THREAD

**Issue by InnovationinProgress** [huggingface/deep-rl-class#409]
Text in example says: 
"If the organizers determined that K=16 and A wins, the new rating would be:"

and

"If the organizers determined that K=16 and B wins, the new rating would be:"

But there is no number to show what it 'would be'

**Comment by simoninithomas** [comment]
Hey there 👋 that's because we have a latex visualization bug in the course my colleague (front end) is working on it. Keep you updated.

In the meantime what you can do is read using mdx file instead: https://github.com/huggingface/deep-rl-class/blob/main/units/en/unit7/introduction.mdx

**Comment by simoninithomas** [comment]
The problem has been solved thanks for pointing this out 🤗
