### ISSUE TITLE
Unit 6: Illustration needs an update to work with the dark theme

### ISSUE THREAD

**Issue by medvedev** [huggingface/deep-rl-class#413]
# What do you want to improve?

In the Unit 6, there's an image with black text on a transparent background. It looks unreadable in a dark theme.
URL: https://huggingface.co/learn/deep-rl-course/unit6/advantage-actor-critic
![image](https://github.com/huggingface/deep-rl-class/assets/439909/08cc7747-69eb-48ee-85df-417e3c792b4f)

**Comment by simoninithomas** [comment]
Hey, thanks for pointing this out 🤗 I updated it.
