### ISSUE TITLE
[UPDATE] A small correction

### ISSUE THREAD

**Issue by olavomendes** [huggingface/deep-rl-class#422]
Three space are missing on the UNIT 2 -> The two types of value-based methods -> The action-value function.

![Screenshot_2](https://github.com/huggingface/deep-rl-class/assets/56777019/dc9ea017-846d-4ad6-8a94-48deb6234243)

**Comment by simoninithomas** [comment]
Hey, thanks for pointing this out 🤗 i'm adding it for the next update
