### ISSUE TITLE
[HANDS-ON BUG]

### ISSUE THREAD

**Issue by varun-sappa** [huggingface/deep-rl-class#434]
# Describe the bug

**Please share your notebook link so that we can reproduce the error**
google colab link is unaccessable, raises error 
There was an error loading this notebook. Ensure that the file is accessible and try again.
https://colab.research.google.com/github/huggingface/deep-rl-class/blob/**master**/notebooks/unit1/unit1.ipynb

# Material

 - Did you use Google Colab?
 - Yes

If not:
 - Your Operating system (OS)
 - Version of your OS

**Comment by varun-sappa** [comment]
The links work by changing master to main in the URL.

**Comment by simoninithomas** [comment]
Hey there 👋 where is located this link? Thanks

**Comment by varun-sappa** [comment]
hello!
[1] https://huggingface.co/learn/deep-rl-course/unit1/hands-on
[2]https://huggingface.co/learn/deep-rl-course/unit2/hands-on

**Comment by simoninithomas** [comment]
Thanks for the PR I merge it 🤗
