### ISSUE TITLE
[UPDATE] Formula Formatting Issuse in pg-theorem

### ISSUE THREAD

**Issue by Ginurx** [huggingface/deep-rl-class#438]
The last equal sign in the equation chain should be on a new line. The current format suggests equivalence where there is none, which is misleading.

![image](https://github.com/huggingface/deep-rl-class/assets/586349/28f9414e-2ae9-4129-b6b6-d74b71ed282f)

**Comment by simoninithomas** [comment]
Thanks for pointing this out I’m adding this to december update

**Comment by simoninithomas** [comment]
Finally merged 😄 thanks again
