### ISSUE TITLE
[UPDATE] The GPU Step 2 image has to be updated in the Unit 01 - Google Colab - Hardware Accelerator

### ISSUE THREAD

**Issue by ashwinsnambiar** [huggingface/deep-rl-class#442]
The section in hands on training for unit 01 and bonus unit 01 has an example image of how the Google Colab hardware accelerator selection should look like. The image shown seems to be an old one. The current one shows up as below. 

![Screenshot from 2023-12-16 14-36-18](https://github.com/huggingface/deep-rl-class/assets/124048775/f1cc1fa3-ea4d-45c9-90bd-847c1752e3be)

**Comment by simoninithomas** [comment]
Thanks for pointing this out I've just updated the illustration. Thanks 🤗
