### ISSUE TITLE
[UPDATE]TYPO: Bonus Unit 1 - ML agents parameters

### ISSUE THREAD

**Issue by ashwinsnambiar** [huggingface/deep-rl-class#443]
The run-id parameter has been incorrectly written with an underscore instead of the hypen
![Screenshot from 2023-12-16 21-51-53](https://github.com/huggingface/deep-rl-class/assets/124048775/78421664-1975-4046-b8cd-f648fed10f29)

**Comment by simoninithomas** [comment]
Thanks I just updated it 🤗
