### ISSUE TITLE
[UPDATE] Add notebook for unit 7 

### ISSUE THREAD

**Issue by varun-sappa** [huggingface/deep-rl-class#447]
# What do you want to improve?
Add notebook for unit 7
- Explain the typo/error or the part of the course you want to improve
There isn't a notebook available for Unit 7 on the repository, so I'd like to create the notebook. This way, we can directly start working on a local PC.

- **Also, don't hesitate to open a Pull Request with the update**.

**Comment by simoninithomas** [comment]
Hey there 👋 , there's no notebook for Unit 7 because it would take too much time to train on a notebook that everytime you'll get a timeout.
