### ISSUE TITLE
[UPDATE] Potentially incorrect terminology in unit 2 midway recap

### ISSUE THREAD

**Issue by lutzvdb** [huggingface/deep-rl-class#451]
# What do you want to improve?

In Unit 2 (Midway Recap) (units/en/unit2/mid-way-recap.mdx) the following is stated:
`There are two types of methods to learn a policy for a value function:`

Now, I'm only just learning all about reinforcement learning, but before, it was clearly stated that for the value-based methods the function was pre-defined and fixed. I think it could be more appropriate to say something along the lines of:

`There are two types of methods to update the value function`

Please let me know if I'm misunderstanding; however, to me, this seems misleading and makes understanding harder.

**Comment by simoninithomas** [comment]
Hey there 👋 ,
Indeed you're right we can change this to what you wrote.

Do you want to open a PR with your phrase so that you can be added as contributor? 🤗

**Comment by lutzvdb** [comment]
Thank you for your answer! I opened [PR 466](https://github.com/huggingface/deep-rl-class/pull/466) accordingly. 

Cheers :)

**Comment by simoninithomas** [comment]
Merged and thanks again 🤗
