### ISSUE TITLE
Arrow showing wrong direction to take for step

### ISSUE THREAD

**Issue by dondev01** [huggingface/deep-rl-class#456]
An image found in [Policy based methods](https://huggingface.co/learn/deep-rl-course/unit1/two-methods#policy-based) shows the incorrect direction to take on a particular step.

![image](https://github.com/huggingface/deep-rl-class/assets/78077453/06e37759-fea9-4782-83b7-606a381512c7)

The arrow is pointing **down**, but it should be pointing to the **right**.

**Comment by simoninithomas** [comment]
Thanks I added it to January update. I'll close the issue when the january update will be merged 🤗

**Comment by simoninithomas** [comment]
Updated thanks 🤗 
![image](https://github.com/huggingface/deep-rl-class/assets/13088472/ea6d2caf-8334-4799-9800-c3edda870881)
