### ISSUE TITLE
[HANDS-ON BUG] huggingface-projects/AIvsAI-SoccerTwos not working

### ISSUE THREAD

**Issue by louisreberga** [huggingface/deep-rl-class#461]
Just to report that huggingface-projects/AIvsAI-SoccerTwos is not working. 
I'm using this link : https://huggingface.co/spaces/huggingface-projects/AIvsAI-SoccerTwos

**Comment by simoninithomas** [comment]
Thanks I'm relaunching the machine

**Comment by louisreberga** [comment]
Great, works now. But I can't see my model on the leaderboard. Am I missing something ?
My model link: https://huggingface.co/rbrgAlou/poca-SoccerTwos

**Comment by simoninithomas** [comment]
I relaunch the machine. But did you tried to visualize your agent playing with our Space? https://huggingface.co/spaces/unity/ML-Agents-SoccerTwos

**Comment by louisreberga** [comment]
Yes, and it works well but no sign of the model in the leaderboard...

**Comment by simoninithomas** [comment]
Hey there 👋 we have some problems with this Unit, we're going to make a clean update on it next month. Since many students get problems.
