### ISSUE TITLE
[HANDS-ON BUG] Unzip commands in unit 5 not working

### ISSUE THREAD

**Issue by JonasDeBoeck** [huggingface/deep-rl-class#464]
# Describe the bug

The unzip commands in the unit 5 hands on do not work. There appears to be something wrong with either the command or the zip files.

# Material

 - Did you use Google Colab? Yes

**Comment by lambdavi** [comment]
The previous method works fine.
As alternative, you could also use the **gdown** library that should be already available on Colab.

```
import gdown

url = 'https://drive.usercontent.google.com/download?id=1YHHLjyj6gaZ3Gemx1hQgqrPgSS2ZhmB5&export=download&authuser=0&confirm=t&uuid=c9ceff01-ddd3-4499-ae40-5f65009b7455&at=APZUnTXTjoZFy5T2Si5Syfq5LHIr%3A1705317052496'
output_path = './training-envs-executables/linux/SnowballTarget.zip'
gdown.download(url, output_path, quiet=False, fuzzy=True)
```
Let me know if this helped.

**Comment by simoninithomas** [comment]
Hey there 👋 we modified the units that were using wget with Drive 🤗
