### ISSUE TITLE
How do i run Unit-3 Hands on Experiment on Local Machine?

### ISSUE THREAD

**Issue by bantu-4879** [huggingface/deep-rl-class#465]
I downloaded the unit3.ipynb and run this file in jupyter notebook. I debuged some problems but it is stuck at this code - 
```
!python -m rl_zoo3.train --algo dqn  --env SpaceInvadersNoFrameskip-v4 -f logs/ -c dqn.yml
```
i used different code - 
```
python -m path.to.rl_zoo3.train --algo dqn --env SpaceInvadersNoFrameskip-v4 -f logs/ -c dqn.yml
```
Even this one is not working after many modifications. This is the error showing  ```UsageError: option --algo not recognized ( allowed: "nidtN:b:pD:l:rs:T:em:G" ) ```

I have not run any deep RL algorithm before on the local machine. 
@simoninithomas

**Comment by simoninithomas** [comment]
Hey there 👋 , did you follow the installation here: https://github.com/DLR-RM/rl-baselines3-zoo?tab=readme-ov-file#installation

The command to train looks like this:

python train.py --algo algo_name --env env_id

**Comment by bantu-4879** [comment]
It worked @simoninithomas 
problem was 
```
!python3 -m rl_zoo3.train --algo dqn  --env SpaceInvadersNoFrameskip-v4 -f logs/ -c dqn.yml
```
I didn't use 3 after python 🥲
