### ISSUE TITLE
[BUG] Example video, unit 3 hands-on colab, not working

### ISSUE THREAD

**Issue by FelipoCruz** [huggingface/deep-rl-class#471]
# What do you want to improve?

- Explain the typo/error or the part of the course you want to improve
- 
[BUG] Example video, unit 3 hands-on colab, not working

This one:
%%html
<video controls autoplay><source src="https://huggingface.co/ThomasSimonini/ppo-SpaceInvadersNoFrameskip-v4/resolve/main/replay.mp4" type="video/mp4"></video>

- **Also, don't hesitate to open a Pull Request with the update**.

**Comment by simoninithomas** [comment]
Hey there 👋 did you used the google colab notebook or the hands-on version?
