### ISSUE TITLE
[HANDS-ON BUG] Bonus Unit 1 Train Huggy

### ISSUE THREAD

**Issue by suhaskr** [huggingface/deep-rl-class#478]
# Describe the bug

Seems there is an issue with the code cell that is used to download the Huggy.zip environment executable file. When I run it, only the first chunk is downloaded.  
The actual file size ~37Mb  
But when the code cell is executed, only the first chunk is downloaded and the cell terminates with success. (the size of the downloaded file is ~2Mb)  

![image](https://github.com/huggingface/deep-rl-class/assets/16692642/16421261-911b-43f9-b6a0-56be202df2fd)

  
# Material
I used Google Colab to execute the code cells.

**Comment by rgargente** [comment]
Hey, I'm having the same issue! Did you manage to solve it?

**Comment by jarles33** [comment]
I have the same problem, the wget script does not work.

As a workaround, I downloaded the 37MB file from the google drive link they provide.
Then right click the folder "linux" and upload the 37MB version.

<img width="220" alt="image" src="https://github.com/huggingface/deep-rl-class/assets/148379470/1cb1b339-063b-46c8-a7ce-87712f54a4a1">

Still, it will be better if huggingface can fix the download script in the notebook.

**Comment by simoninithomas** [comment]
Hey there 👋 this error has been solved we changed from Google Drive to Github.

We updated Huggy notebook.

If you still have issues don't hesitate to comment below. For now I'm closing the issue.
