### ISSUE TITLE
[UPDATE] Duplicate image in Unit 3 - The Deep Q Algorithm

### ISSUE THREAD

**Issue by PierreCounathe** [huggingface/deep-rl-class#479]
# What do you want to improve?

- In Unit 3. Deep Q Algorithm, there is the same image twice, I thought maybe the goal was either to set the second image to show the training phase  (with a purple box), or maybe that's just a duplicate?
<img width="561" alt="Screenshot 2024-01-31 at 7 06 00 PM" src="https://github.com/huggingface/deep-rl-class/assets/72037857/cc9815bb-da79-4fb1-838c-a41fcd3bd487">

[code link](https://github.com/huggingface/deep-rl-class/blob/d7ec1b4ae3887d06001768b130bbfafd6fc9bc33/units/en/unit3/deep-q-algorithm.mdx#L52)

- Cannot open a PR as I don't have access to the images

**Comment by simoninithomas** [comment]
Hey there 👋 , no it's made on purpose, first we talk about Experience replay. But if people scroll they can't see the image anymore and since we continue to explain how we use Experience Replay I decided to put the image again.

**Comment by PierreCounathe** [comment]
Hi Thomas, ok that's clear, I'll close the issue, thanks.
