### ISSUE TITLE
[HANDS-ON BUG] unit5 hands on Pyramids

### ISSUE THREAD

**Issue by IrinaArcadievna** [huggingface/deep-rl-class#480]
# Describe the bug
I have a bug in Unit5 hands on part 2 - Pyramids. Unzip do not work
- Did you use Google Colab?
Yes

**Comment by MatthewZhang473** [comment]
## Here's what works for me:
1. Download the zip file to your own laptop:[as provided in the notebook]([https://drive.google.com/uc?export=download&id=1UiFNdKlsH0NTu32xV-giYUEVKV4-vc7H](https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Fdrive.google.com%2Fuc%3Fexport%3Ddownload%26id%3D1UiFNdKlsH0NTu32xV-giYUEVKV4-vc7H))
2. Create a public Github repository, and add this file to the repo.
3. Clone the repository from your Colab, and unzip the file accordingly.

**Comment by IrinaArcadievna** [comment]
Thanks

**Comment by simoninithomas** [comment]
Hey there 👋 , we updated last week the notebook. Indeed there was a problem with Google Drive. Thanks for pointing this out 🤗 .
