### ISSUE TITLE
[HANDS-ON BUG] Typos in the material Bonus Unit 2

### ISSUE THREAD

**Issue by ZhenghaoYang19** [huggingface/deep-rl-class#482]
# Describe the bug
<img width="522" alt="image" src="https://github.com/huggingface/deep-rl-class/assets/87429104/0ed247ee-636e-43c5-a222-c03463431d3d">
The N_EVALUATIONS (which =2) should be replaced with N_TIMESTEPS here
**Please share your notebook link so that we can reproduce the error**

# Material

 - Did you use Google Colab?
Yes
If not:
 - Your Operating system (OS)
 - Version of your OS

**Comment by simoninithomas** [comment]
Hey there 👋 this section was not made by us. It's a link from [Antonin’s Raffin ICRA 2022 presentations](https://araffin.github.io/tools-for-robotic-rl-icra2022/).  So we can't modify the content.
