### ISSUE TITLE
[HANDS-ON BUG]

### ISSUE THREAD

**Issue by minhquanch2** [huggingface/deep-rl-class#491]
# Describe the bug
I knew that this error would definitely happen when I run the code. However I didn't know where to create the file 'dqn.yml' and also the logs folder. The error is given below
FileNotFoundError: [Errno 2] No such file or directory: 'dqn.yml'
Hopefully you can make it easier for running all the codes the same way as you give the solutions for each line of code. 

# Material
I used the Google Collab for running the given code.

**Comment by simoninithomas** [comment]
Hey there 👋 

I suppose you talk about Unit 3

Normally you learned to create a file in Unit bonus 1: https://github.com/huggingface/deep-rl-class/blob/main/notebooks/bonus-unit1/bonus-unit1.ipynb

But you're right we should add an explanation in this unit too. I'm adding it to the roadmap
