### ISSUE TITLE
[UPDATE] An error in quiz 2

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [huggingface/deep-rl-class#492]
# What do you want to improve?

- Explain the typo/error or the part of the course you want to improve

- **Also, don't hesitate to open a Pull Request with the update**.

In second quiz, there is such a problem.
![image](https://github.com/huggingface/deep-rl-class/assets/60914359/a0f81cc2-26c3-4a29-8081-99b9cda5d9fc)

However, the third option is the definition of Q-function instead of Q-learning. 
![image](https://github.com/huggingface/deep-rl-class/assets/60914359/861a16f4-0f05-4012-b877-008aa6c4a153)

So it should not be included as the answer.

**Comment by simoninithomas** [comment]
Thanks 🤗 I merged the PR. I'm closing the issue
