### ISSUE TITLE
[UPDATE] An unproper description in the Prerequisites in unit1.ipynb

### ISSUE THREAD

**Issue by Croolch** [huggingface/deep-rl-class#501]
# What do you want to improve?

I suggest listing some concepts that are more relative such as RL process in the prerequisites in unit1.ipynb.

- Explain the typo/error or the part of the course you want to improve

There are no concepts explained in Unit 1 such as MC, TD. It may cause some confusions when someone read about it as a learner.

- **Also, don't hesitate to open a Pull Request with the update**.

https://github.com/huggingface/deep-rl-class/pull/500

**Comment by simoninithomas** [comment]
Thanks for pointing this out 🤗 I merged your PR. I'm closing this issue.
