### ISSUE TITLE
[QUESTION] Why is Unit 7 missing

### ISSUE THREAD

**Issue by Ymriri** [huggingface/deep-rl-class#505]
1. First, the **best way to get a response fast is to ask the community** it on #rl-study-group in our Discord server: https://www.hf.co/join/discord
 Emmm, I'm having a little trouble  with "ERR_CONNECTION_CLOSED".
2. If you prefer you can ask here, please **be specific**.
When I study on this [page](https://huggingface.co/blog/deep-rl-a2c), click "Start the tutorial here 👉". But show 404!

**Comment by simoninithomas** [comment]
Hey there 👋 
1. The website: https://hf.co/join/discord
2. It's the former version of the course: ⚠️ A new updated version of this article is available here 👉 https://huggingface.co/learn/deep-rl-course/unit6/introduction
