### ISSUE TITLE
Unable to Publish to repo [HANDS-ON BUG]

### ISSUE THREAD

**Issue by dbostain** [huggingface/deep-rl-class#508]
# Describe the bug

[**Please share your notebook link so that we can reproduce the error**]
(https://github.com/dbostain/Daves-Typing/blob/main/notebooks/unit1/unit1.ipynb)

# Material
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    285     try:
--> 286         response.raise_for_status()
    287     except HTTPError as e:

13 frames
HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/repos/create

The above exception was the direct cause of the following exception:

HfHubHTTPError                            Traceback (most recent call last)
HfHubHTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/repos/create (Request ID: Root=1-65f6cc9c-142137a02aae9d4c3b597262;e9f0566d-924d-47c8-a1da-897544914c90)

You don't have the rights to create a model under the namespace "DaveBostain"

During handling of the above exception, another exception occurred:

HTTPError                                 Traceback (most recent call last)
HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/DaveBostain/ppo-LunarLander-v2

The above exception was the direct cause of the following exception:

RepositoryNotFoundError                   Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    321                 " make sure you are authenticated."
    322             )
--> 323             raise RepositoryNotFoundError(message, response) from e
    324 
    325         elif response.status_code == 400:

RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-65f6cc9c-350ad05b7415e33e247048e5;8a1561bd-87fb-4965-bf3e-d541144fedb3)

Repository Not Found for url: https://huggingface.co/api/models/DaveBostain/ppo-LunarLander-v2.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

If not:
 - Your Operating system (OS)
 - Version of your OS

**Comment by simoninithomas** [comment]
Hi, DaveBostain seems to not exist in our HF users. Are you sure you wrote it correctly? It's important to have the same name than your HF username otherwise you can't push.
For instance, my username is ThomasSimonini not thomassimonini

You can find your username when you go to your profile and check the url: https://huggingface.co/ThomasSimonini

**Comment by dbostain** [comment]
I will check ThomasSimonini.

Thanks!

dbostain
