### ISSUE TITLE
[HANDS-ON BUG] Unit 3 error while running "virtual_display = Display(visible=0, size=(1400, 900))"

### ISSUE THREAD

**Issue by kelvinho8** [huggingface/deep-rl-class#512]
# Describe the bug

**Please share your notebook link so that we can reproduce the error**

virtual_display = Display(visible=0, size=(1400, 900))

================================
An error below occurred while running script above
================================
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-6-6a8c1d860fe4>](https://localhost:8080/#) in <cell line: 4>()
      2 from pyvirtualdisplay import Display
      3 
----> 4 virtual_display = Display(visible=0, size=(1400, 900))
      5 virtual_display.start()

5 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, restore_signals, gid, gids, uid, umask, start_new_session)
   1861                     if errno_num != 0:
   1862                         err_msg = os.strerror(errno_num)
-> 1863                     raise child_exception_type(errno_num, err_msg, err_filename)
   1864                 raise child_exception_type(err_msg)
   1865 

FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'

# Material

 - Did you use Google Colab? yes, unit 3

If not:
 - Your Operating system (OS)
 - Version of your OS

**Comment by ztchir** [comment]
I was experiencing this issue as well. It looks to be an issue with repo and collab updates.

I found this post helped as a temporary work around (https://github.com/tensorflow/agents/issues/314):

updating apt with `!sudo apt-get update` before installing xvfb and python-opengl

**Comment by simoninithomas** [comment]
Yes unfortunately that's a usual bug with Xvfb in colab. The solution provided by @ztchir is one of the solution for now.
