### ISSUE TITLE
[UPDATE] : Unit 3 DQN 

### ISSUE THREAD

**Issue by pdx97** [huggingface/deep-rl-class#516]
# What do you want to improve?
- You could add a bonus unit in Unit Three where you talk about the Q Learning and its importance as the discount factor determines how much the reinforcement learning agents cares about rewards in the distant future relative to those in the immediate future. 
- If γ=0, **the agent will be completely myopic** and only learn about actions that produce an immediate reward. 
- If γ=1, **the agent will evaluate each of its actions based on the sum total of all of its future rewards**

- Explain the typo/error or the part of the course you want to improve
Add Gamma and its significance .
I believe its a important thing to tell as DQNs are very sensitive to Hyperparameters.

**Comment by pdx97** [comment]
ohh then its fine , if you have already mentioned it in the Q learning , I might have missed it . 😊

**Comment by simoninithomas** [comment]
Ok, in that case I'm closing the issue 🤗
