### ISSUE TITLE
[HANDS-ON BUG] Deprecated Python 2 dependeny on the course can no longer be installed

### ISSUE THREAD

**Issue by duckladydinh** [huggingface/deep-rl-class#528]
# Describe the bug

![Screenshot from 2024-05-10 23-07-59](https://github.com/huggingface/deep-rl-class/assets/22922064/59363686-bd87-4ac6-a68e-0401cc3fcb3b)

The Deep RL course Unit 1 Hands-on uses a deprecated Python2 dependency that can't be installed anymore on Google Colab.

# Material

 - Did you use Google Colab? Yes.

**Comment by simoninithomas** [comment]
Hi 👋  thanks for the bug solving, I merged it 🤗
