### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'results/Huggy/configuration.yaml'

### ISSUE THREAD

**Issue by qboy21** [huggingface/deep-rl-class#530]
# Describe the bug
No configuration.yaml file for results found and unable to save trained model to HF.
1
!mlagents-push-to-hf --run-id="HuggyTraining" --local-dir="./results/Huggy" --repo-id="ThomasSimonini/ppo-Huggy" --commit-message="Huggy"

[INFO] This function will create a model card and upload your HuggyTraining into HuggingFace Hub. This is a work in progress: If you encounter a bug, please send open an issue
Traceback (most recent call last):
  File "/usr/local/bin/mlagents-push-to-hf", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-push-to-hf')())
  File "/content/ml-agents/ml-agents/mlagents/utils/push_to_hf.py", line 205, in main
    package_to_hub(
  File "/content/ml-agents/ml-agents/mlagents/utils/push_to_hf.py", line 159, in package_to_hub
    _generate_config(local_path, configfile_name)
  File "/content/ml-agents/ml-agents/mlagents/utils/push_to_hf.py", line 29, in _generate_config
    with open(os.path.join(local_dir, configfile_name)) as yaml_in:
FileNotFoundError: [Errno 2] No such file or directory: 'results/Huggy/configuration.yaml'

# Material
Google Colab
Trained successfully with no issue
Saved original yaml file.

**Comment by adyachok** [comment]
It looks like you need to update this argument **--local-dir="./results/Huggy"** to **--local-dir="./results/Huggy2"**
