### ISSUE TITLE
[HANDS-ON BUG] boolean is a digital number other than 1 or 0

### ISSUE THREAD

**Issue by nanxusu** [huggingface/deep-rl-class#532]
# Describe the bug
https://colab.research.google.com/github/huggingface/deep-rl-class/blob/master/notebooks/unit1/unit1.ipynb?authuser=1#scrollTo=ZNPG0g_UGCfh

For unit1.ipynb, the final two values of the 8-dimention observation should be: _If the left leg contact point has touched the land_ (boolean) and _If the right leg contact point has touched the land_ (boolean). 

However, the `env.observation_space.sample()` returned _[-66.26277     87.800964     4.018273     3.077604    -0.1319175 -2.6315386    0.20755419   0.5502597 ]_, where the final two values are not boolean. 

# Material

 - Did you use Google Colab?

If not:
 - Your Operating system (OS)
 - Version of your OS

**Comment by simoninithomas** [comment]
Hi, I'm agree with you but the official document seems to say https://gymnasium.farama.org/environments/box2d/lunar_lander/ that it's two boolean, I think the best is to open an issue to https://github.com/Farama-Foundation/Gymnasium
