### ISSUE TITLE
No google colab button available in the Unit-3 during hands on for Deep RL Course

### ISSUE THREAD

**Issue by Gruhit13** [huggingface/deep-rl-class#536]
I am currently in the hands on section in unit 3 of Deep RL course but in that I am not getting any button for google colab where as in the section it states that "To start the hands-on click on Open in Colab button". But there is no button to direct to the colab button. 

![image](https://github.com/huggingface/deep-rl-class/assets/64111603/5ff29740-5d26-4f73-9c9c-72c9deaa0907)

**Comment by simoninithomas** [comment]
Hey there 👋  can you tell me what is your browser and its version? Because on mine (Chrome) I see the button

<img width="678" alt="Screenshot 2024-06-10 at 16 30 59" src="https://github.com/huggingface/deep-rl-class/assets/13088472/d1df319b-8ee1-43ee-8d20-1d4f8517c38e">

**Comment by Gruhit13** [comment]
This is my chrome version
[image: image.png]

When I inspected the source there I can see a paragraph tag that has the
link to google colab, but the corresponding image(.svg) is not being loaded
due to some reason.

I guess using the source inspect to go to colab will serve as a work
around.

**Comment by simoninithomas** [comment]
Hi, the image you sent didn't loaded but I checked again with my chrome and it works 🤔 .

**Comment by Gruhit13** [comment]
It is alright, I guess there is some issue with my browser as when opening
the same link in another browser it works.

Thank You for responding and assisting me with this issue. Also please
bring courses like this it is extremely helpful and great to learn.

Thank You,
Gruhit Patel

**Comment by simoninithomas** [comment]
You're welcome. And thanks for the nice feedback 🤗

**Comment by Gruhit13** [comment]
Hello Thomas,
I have recently completed training a PPO agent for playing a Snowball
shooting game and pushed my model to hugging face GitHub but I am not able
to see the video. I am also not able to find my model on
https://huggingface.co/unity. I request your assistance in this matter.

Thank You,
Gruhit Patel
