### ISSUE TITLE
[HANDS-ON BUG]

### ISSUE THREAD

**Issue by coderNODEZ** [huggingface/deep-rl-class#538]
Nothing seems to work with these HuggingFace courses. I try this in the evening after work, and the following link does not work at all...
[https://huggingface.co/spaces/ThomasSimonini/ML-Agents-SnowballTarget](https://www.google.com/url?q=https%3A%2F%2Fhuggingface.co%2Fspaces%2FThomasSimonini%2FML-Agents-SnowballTarget)

My model seems to have loaded to the repo ... then the link above does not allow me see the model in action. 
# Describe the bug

**Please share your notebook link so that we can reproduce the error**

# Material

 - Did you use Google Colab?

If not:
 - Your Operating system (OS)
 - Version of your OS

**Comment by coderNODEZ** [comment]
Windows 11 and yes I used colab.

**Comment by coderNODEZ** [comment]
I did try to enter the username like 50 times.

**Comment by coderNODEZ** [comment]
These directions also do not work ?!?!  the model is nowhere to be found!

If the environment is part of ML-Agents official environments, go to https://huggingface.co/unity
Step 1: Find your model_id: zetimetomldlrl/ppo-SnowballTarget
Step 2: Select your .nn /.onnx file
Click on Watch the agent play 👀

**Comment by simoninithomas** [comment]
Hey there 👋 ,

1. The link you provided me seems to work: https://huggingface.co/spaces/ThomasSimonini/ML-Agents-SnowballTarget
2. Can you give me your username so that I can check for your model?

**Comment by coderNODEZ** [comment]
Thanks for your time with this. I'll take another look at that. I have been quite busy.
