### ISSUE TITLE
unit3 error message when pushing model to hugging face

### ISSUE THREAD

**Issue by foye501** [huggingface/deep-rl-class#539]
# Describe the bug
 in unit3 I run into error message when pushing model to hugging face? 

<img width="700" alt="Screenshot 2024-06-12 at 16 05 12" src="https://github.com/huggingface/deep-rl-class/assets/36092981/ecb764d3-94f5-433a-8f6e-a76c721f4d1a">

**Please share your notebook link so that we can reproduce the error**

# Material

 - Did you use Google Colab?
 yes

If not:
 - Your Operating system (OS)
 - Version of your OS

**Comment by simoninithomas** [comment]
Hey there 👋 

Did you tried to just run solutions of the notebook to test if it works correctly?

If yes, please provide your notebook link so that I can check what's the problem

**Comment by foye501** [comment]
> Hey there 👋
> 
> Did you tried to just run solutions of the notebook to test if it works correctly?
> 
> If yes, please provide your notebook link so that I can check what's the problem

Yes, I have just try the solution except that of pushing model. It failed again, I guess maybe the version of some package doesn't right. Thank you for your help.

this is my notebook https://colab.research.google.com/github/huggingface/deep-rl-class/blob/main/notebooks/unit3/unit3.ipynb#scrollTo=co5um_KeKbBJ

**Comment by simoninithomas** [comment]
So I tested it and it work correctly:

1. Did you changed orga here with your username (beware that if you have MAJ it takes into account, for instance my username is ThomasSimonini not thomassimonini).

!python -m rl_zoo3.push_to_hub  --algo dqn  --env SpaceInvadersNoFrameskip-v4  --repo-name dqn-SpaceInvadersNoFrameskip-v4vvvv  **-orga ThomasSimonini**  -f logs/

3. When you put your write token above did it says your token was correct?

**Comment by foye501** [comment]
> So I tested it and it work correctly:
> 
> 1. Did you changed orga here with your username (beware that if you have MAJ it takes into account, for instance my username is ThomasSimonini not thomassimonini).
> 
> !python -m rl_zoo3.push_to_hub --algo dqn --env SpaceInvadersNoFrameskip-v4 --repo-name dqn-SpaceInvadersNoFrameskip-v4vvvv **-orga ThomasSimonini** -f logs/
> 
> 3. When you put your write token above did it says your token was correct?

Thank you, I tried it again. I am sure that I loged in using the tokens. but I still face the keyerror, this is my copy of notebook. 
https://colab.research.google.com/drive/13R97v7Xcyyn-qFao4iyuC1ywgBzvDngE#scrollTo=2RVEdunPHs8B

**Comment by foye501** [comment]
It creates a empty folder in my huggingface ,
https://huggingface.co/foye501/SpaceInvadersNoFrameskipv4

**Comment by simoninithomas** [comment]
I don't have access to your notebook I just asked access.

**Comment by foye501** [comment]
> I don't have access to your notebook I just asked access.

Thank you

**Comment by simoninithomas** [comment]
Hi, I tried from scratch it seems to work.
Are you sure you didn't missed a step: 
- Did you created dqn.yml?
- Did your read the messages after the training? If it wasn't saved etc?

For me the best is take the notebook from scratch: a new version of the notebook.

**Comment by foye501** [comment]
Thank you, I will try it again, Thank you.

**Comment by foye501** [comment]
> Thank you, I will try it again, Thank you.

Thank you, I will try it again, Thank you.

> Hi, I tried from scratch it seems to work. Are you sure you didn't missed a step:
> 
> * Did you created dqn.yml?
> * Did your read the messages after the training? If it wasn't saved etc?
> 
> For me the best is take the notebook from scratch: a new version of the notebook.

Thank you, I will try it again, Thank you.

**Comment by simoninithomas** [comment]
I'm closing the issue for now, if there's still an issue after your new tries, please open a new one 🤗

**Comment by joaquinfeltes** [comment]
Hi! I´m having the same problem. I used all the provided solutions, I created the yml file and the logs folder was created also. Could this be a problem with a package version? 
I saw [this](https://discuss.huggingface.co/t/why-am-i-getting-keyerror-email/89188) error that seems related.
Thanks for the help!
