### ISSUE TITLE
Where do I download my certificate?

### ISSUE THREAD

**Issue by M2LabOrg** [huggingface/deep-rl-class#542]
1. First, the **best way to get a response fast is to ask the community** it on #rl-study-group in our Discord server: https://www.hf.co/join/discord

2. If you prefer you can ask here, please **be specific**.
I have just completed the course including all of the assignments. The objective was to learn more about Deep RL and to receive a certificate. However, I have not received any information or email regarding how to download the certificate. Please advice. 
You can check my assignments through my HF username: M2LabOrg
Thank you!

**Comment by simoninithomas** [comment]
Hi, you can download the certificate by:
- Going there: https://huggingface.co/spaces/huggingface-projects/Deep-RL-Course-Certification
- Fill the form
- And click on the ⬇️ arrow


<img width="1376" alt="Screenshot 2024-06-21 at 12 07 07" src="https://github.com/huggingface/deep-rl-class/assets/13088472/1c198bb3-4c0f-463a-8df7-b12f5e20e73e">

**Comment by M2LabOrg** [comment]
Hi @simoninithomas ,
Thank you so much for your message and for creating such an amazing course! 
Best wishes,
Michel
