### ISSUE TITLE
[HANDS-ON BUG]: Unit7 / hands-on / Step4 / instructions not included for Ubuntu or Linux

### ISSUE THREAD

**Issue by ra9hur** [huggingface/deep-rl-class#544]
# Describe the bug
I am working in Ubuntu environment. With regard to Unit7 / hands-on / Step 4:

1. When I navigate to training-envs-executables folder on my local machine, SoccerTwos executable is not available.
2. Is that the reason that command-line instructions for Ubuntu to run mlagents-learn is not included in hands-on / Step 4 ? If YES, can you please clearly mention this in  the instructions and possible alternatives to proceed with the project ?
3. Is there an external source (like github) from where I can download the executable, copy this to my local folder and then run ?
4. I created a soccer playground in Unity. However, finding it difficult with scripts to cover for collaborative and competitive functionality. Could not find many related resources on YouTube. Can you please point me to any reference implementation ?

![soccer_playground](https://github.com/huggingface/deep-rl-class/assets/17127066/7232a4e1-815c-4590-bfd4-a4a7e347ad32)

 - Your Operating system (OS): Ubuntu
 - Version of your OS: 22.04

**Comment by pandita-IA** [comment]
Hi, today I have just finished the tutorial form Unit 7 using a Linux distribution and it is true that not everything is clear for linux users but i managed at the end to finish training my model.

As it is said in the tutorial there is a executable download for linux 
Linux (Ubuntu): Download [this executable] (go to the link of the drive of Unit 7).

and the command for linux would be something like this:
mlagents-learn ./config/poca/SoccerTwos.yaml --env=./training-envs-executables/SoccerTwos.x86_64 --run-id="SoccerTwos" --no-graphics

Maybe it is not everything that you would need but I hope it can help you at least trying the model.

**Comment by simoninithomas** [comment]
Hi

1. In the tutorial there's the ubuntu executable that you can use to train your model.

2. I think the command written by @pandita-IA is the correct one for ubuntu.

3. Yes in step 0: https://huggingface.co/learn/deep-rl-course/en/unit7/hands-on#step-0-install-mlagents-and-download-the-correct-executable
To see your agent playing on Space you can use this space: https://huggingface.co/spaces/unity/ML-Agents-SoccerTwos

4. For that the best resources are:
- On MaPoca: https://unity.com/es/archive/blog/engine-platform/ml-agents-v20-release-now-supports-training-complex-cooperative-behaviors

- On collaboration vs competition: https://unity-technologies.github.io/ml-agents/ML-Agents-Overview/#flexible-training-scenarios

**Comment by ra9hur** [comment]
@pandita-IA  / @simoninithomas ,

Thanks for the quick response. My mistake, oversight on my side. Missed reading instructions in step 0.
I am able to start the run. 

On the additional resources, thanks for those links on MA-POCA and collaboration vs competition. I am sure, it would be of great help !!

**Comment by simoninithomas** [comment]
Glad to hear that don't hesitate to ping me when you have the results 🤗
