### ISSUE TITLE
[UPDATE] Frozen Lake reward

### ISSUE THREAD

**Issue by svetaU** [huggingface/deep-rl-class#563]
Should not Reach hole reward be -1?

**Comment by max-fofanov** [comment]
You can see in the gymnasium documentation, that the reward function is as in the course notebook: https://gymnasium.farama.org/environments/toy_text/frozen_lake/#rewards

**Comment by svetaU** [comment]
Странно 🤔 А как же он тогда в проруби не падает? How does it learn to avoid holes then?

**Comment by max-fofanov** [comment]
> Странно 🤔 А как же он тогда в проруби не падает? How does it learn to avoid holes then?

Если падает в прорубь, это эпизод заканчивается и награда остаётся 0)
If an agent goes into the hole, than the episode is terminated and the reward is 0)
