### ISSUE TITLE
[HANDS-ON BUG] Unit 8 Part 2 package version issue

### ISSUE THREAD

**Issue by TPK-MAKG** [huggingface/deep-rl-class#577]
# Describe the bug

When installing the dependencies needed for the unit, sample-factory does not install due to a package version conflict, presumably with pip.
The error is as follows,

WARNING: Ignoring version 2.0.2 of sample-factory since it has invalid metadata:
Requested sample-factory==2.0.2 from https://files.pythonhosted.org/packages/cd/f9/b64b51f290fb6ab349e51684686865c100de74d1b42f8b39680fcc5f27b6/sample_factory-2.0.2-py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    numpy (>=1.18.1<2.0)
          ~~~~~~~~~^
Please use pip<24.1 if you need to use this version.
ERROR: Could not find a version that satisfies the requirement sample-factory==2.0.2 (from versions: 1.0.5, 1.0.6, 1.0.117, 1.117.1, 1.117.2, 1.117.3, 1.120.0, 1.120.1, 1.120.2, 1.121.0, 1.121.1, 1.121.2, 1.121.3, 1.121.4, 1.123.0, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.1)
ERROR: No matching distribution found for sample-factory==2.0.2

Notebook link: https://colab.research.google.com/github/huggingface/deep-rl-class/blob/master/notebooks/unit8/unit8_part2.ipynb#scrollTo=alxUt7Au-O8e

# Material
Issue while running in Google Colab notebook.

**Comment by simoninithomas** [comment]
Hi, we just merged a PR that update the version of sample-factory installed. It should work now 🤗
