### ISSUE TITLE
Unit 1 Notebook - Issue on package_to_hub cell

### ISSUE THREAD

**Issue by EvanMath** [huggingface/deep-rl-class#68]
Hey,

I want to note in the cell related to the `package_to_hub` package these lines of code:

```
# Create the evaluation env
eval_env = DummyVecEnv([lambda: gym.make(env_id)])
```
should be after:
```
# TODO: Define the name of the environment
env_id = "LunarLander-v2"
```
To avoid `NameError` issues.

Regards

**Comment by simoninithomas** [comment]
Hey there 👋 ,

You're right, it's correct in solution cell but not in the exercise cell. I update it. Thanks 🤗
