### ISSUE TITLE
[lib][RL] Using pytorch-lightning, catalyst-rl, sample-factory

### ISSUE THREAD

**Issue by paantya** [huggingface/deep-rl-class#7]
Can you please tell me how you look at using the following libraries, ideas, for training in a course or research, production and use for reinforcement learning?

1. pytorch-lightning https://www.pytorchlightning.ai/
2. PyTorch Lightning bolts https://github.com/PyTorchLightning/lightning-bolts
3. catalyst-rl https://github.com/catalyst-team/catalyst-rl
4. sample-factory https://github.com/alex-petrenko/sample-factory

What do you think about this?

**Comment by simoninithomas** [comment]
Hi,
Sorry for the delay
For the first version of the course we'll use SB3, RL-Zoo, RLlib and CleanRL.

PyTorch lighting is a powerful library with a very responsive team.
Catalyst-rl is not updated since 2 years so that's not a good sign.
I didn't know about sample-factory I'll check this repo.
