### ISSUE TITLE
goal conditioned RL

### ISSUE THREAD

**Issue by paantya** [huggingface/deep-rl-class#8]
Please tell me if the course will cover the topic of goal conditioned RL?

When with the help of award design, high results are achieved on simple algorithms, comparable to the latest RL SoTA

**Comment by simoninithomas** [comment]
For now we didn't planned to work on Goal Conditioned RL. But you might check Stanford Meta Learning Course that talk about this topic (on Deep RL lectures): https://www.youtube.com/playlist?list=PLoROMvodv4rMC6zfYmnD7UG3LVvwaITY5
