### ISSUE TITLE
Show numerical rank in Leaderboard.

### ISSUE THREAD

**Issue by ghosh-r** [huggingface/deep-rl-class#81]
One of the leaderboards is [a huggingface space here](https://huggingface.co/spaces/ThomasSimonini/Lunar-Lander-Leaderboard). This is what it currently looks like:

![image](https://user-images.githubusercontent.com/58001482/187074205-10df2c06-b348-4683-8717-0e88ea40f677.png)

It does not have any numerical ranks beside the entries. I think it would be very interesting and useful to have a numerical rank beside each entry. In that way, one can know where one stands with respect to others with clear numeric rank.

It would also be useful to have a Kaggle-like percentage ranking. It should show the percentile of the entry for each entry.

Please consider implementing this. It would be very useful if one could say:

* "My model is currently the $n$ -th best model in the leaderboard."
* "My model is in the top $k$ % in the leaderboard."

**Comment by osanseviero** [comment]
I love the idea of having a "rank" column.

**Comment by simoninithomas** [comment]
Hey there 👋 ,

Thanks for the feedback, the space you mentioned is not the latest one it's the old one. **Do you remember where you've got this link so that I can update it?**

In the new one we have the rank: https://huggingface.co/spaces/huggingface-projects/Deep-Reinforcement-Learning-Leaderboard

My model is in the top  k% in the leaderboard: that's a good idea I'm adding that to the list for our new leaderboard we're making with the new version of Gradio 🤗

**Comment by ghosh-r** [comment]
@simoninithomas here is the link: https://huggingface.co/spaces/ThomasSimonini/Lunar-Lander-Leaderboard . It was mentioned in the issue.

In case of where I *got* the link, it is in the Notebook of Section-1. Here is the link: https://github.com/huggingface/deep-rl-class/blob/main/unit1/unit1.ipynb

I got this link from the Intro post itself: https://huggingface.co/blog/deep-rl-intro .

I hope you update it. 😃

**Comment by ghosh-r** [comment]
Thanks for the new link. It's good to see that this one has ranks.

And thanks for seriously considering percentile score.

**Comment by simoninithomas** [comment]
Thanks for the links I'm updating the post and notebook link section.

Yes percentile is a great idea, I'm checking how we're going to do it with the new version of gradio (in terms of UI).

I'll keep you updated 🤗
