### ISSUE TITLE
Unit5 tutorial errors with gym version 0.26.1 . The version is not specified in the tutorial

### ISSUE THREAD

**Issue by c1505** [huggingface/deep-rl-class#88]
* When running the tutorial on google colab, gym version 0.25.2 gets installed currently and things work.  
* Installing on other systems, you get the most recent version by default which is 0.26.1 and it has breaking changes that make it incompatible with code designed to work with 0.25.x

* Suggestion to specify the versions of dependencies in this and other tutorials or the smaller fix would be to just specify the version of gym to be 0.25.x .

**Comment by simoninithomas** [comment]
Hey there 👋 , thanks for the information 🤗 I'm solving this today. Keep you updated.

**Comment by simoninithomas** [comment]
Closing the issue since the new Unit will not use gym thanks for your feedback 🤗
