### ISSUE TITLE
Unit1 Tutorial: The package_to_hub function throws error(NoSuchDisplayException: Cannot connect to "None")

### ISSUE THREAD

**Issue by junjiel** [huggingface/deep-rl-class#89]
Followed the handson tutorial in Unit1 and the package_to_hub function throws an error when trying to push the model to huggingface hub. Below is the error message.

> NoSuchDisplayException                    Traceback (most recent call last)
[<ipython-input-21-3d0d9ab0e512>](https://localhost:8080/#) in <module>
     32                eval_env=eval_env,
     33                repo_id=repo_id,
---> 34                commit_message=commit_message)
     35 
     36 # Note: if after running the package_to_hub function and it gives an issue of rebasing, please run the following code
[/usr/local/lib/python3.7/dist-packages/pyglet/canvas/xlib.py](https://localhost:8080/#) in __init__(self, name, x_screen)
    121         self._display = xlib.XOpenDisplay(name)
    122         if not self._display:
--> 123             raise NoSuchDisplayException('Cannot connect to "%s"' % name)
    124 
    125         screen_count = xlib.XScreenCount(self._display)
NoSuchDisplayException: Cannot connect to "None"

The corresponding code is shown below
```
import gym

from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.env_util import make_vec_env

from huggingface_sb3 import package_to_hub

env_id = "LunarLander-v2"
model_architecture = "PPO"
repo_id = "JJRohan/ppo-LunarLander-v2"
commit_message = "Second commit, revise the process"

package_to_hub(model=model, 
               model_name=model_name,  
               model_architecture=model_architecture, 
               env_id=env_id, 
               eval_env=eval_env, 
               repo_id=repo_id,
               commit_message=commit_message)
```

**Comment by simoninithomas** [comment]
Hi, if you use colab you need to add a virtual display, virtual display is what allow your environment to be rendered.

- Check step 0 of the unit
- Or in this documentation: https://github.com/huggingface/huggingface_sb3#case-3-i-use-google-colab-with-classic-controlbox2d-gym-environments

**Comment by junjiel** [comment]
Thanks! I might have overlooked step 0 when I tried to push the model to hub. It is solved by running step 0.
