### ISSUE TITLE
Unit 5 Tutorial errors and changes to the code

### ISSUE THREAD

**Issue by azamshoaib** [huggingface/deep-rl-class#94]
Hi, there are errors in the unit5. ipynb. I tested for the gym environment 0.24 and 0.26, the errors I got are following:
1. ValueError: too many values to unpack (expected 4) (in reinforce function)
2.  Expected nd_array and tuple ( in policy function)

I have made the following changes in the code, if somebody has problem try to change those functions with the following code

`class Policy(nn.Module):
    def __init__(self, s_size, a_size, h_size):
        super(Policy, self).__init__()
        self.fc1 = nn.Linear(s_size, h_size)
        self.fc2 = nn.Linear(h_size, a_size)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return F.softmax(x, dim=1)
    
    def act(self, state):
        if len(state) == 2:
            state = state[0]
        state = torch.from_numpy(state).float().unsqueeze(0).to(device)
        probs = self.forward(state).cpu()
        m = Categorical(probs)
        action = m.sample()
        return action.item(), m.log_prob(action)`

For reinforce function replace this `state, reward, done, _ = env.step(action)` with this one `state, reward, done, _, _ = env.step(action)`

Similarly for the evaluation function, change this `new_state, reward, done, info = env.step(action)` to this `new_state, reward, done, info, _ = env.step(action)`.

This additional information after the env.step is being reported in the gym as "truncated", as it can be seen from the below code from gym docs `observation, reward, terminated, truncated, info = env.step(action)`

**Comment by simoninithomas** [comment]
Thanks for the issue, as mentioned in Discord I keep that in the issue feed to when I'm updating Unit 5 with the new implementation 🤗

**Comment by simoninithomas** [comment]
I'm working on redoing the unit with a clearer implementation thanks again for your feedback 🤗
