### ISSUE TITLE
Unit 2 Gym version 0.24.0 Warning

### ISSUE THREAD

**Issue by rkrawczyk9** [huggingface/deep-rl-class#97]
A quick small one-

This warning didn't cause any problems, but maybe it would be nice to have a note saying "ignore that error" or something lol

On Unit 2 Step 3 I get this warning (in Colab)...
"Warning: Gym version v0.24.0 has a number of critical issues with `gym.make` such that the `reset` and `step` functions are called before returning the environment. It is recommend to downgrading to v0.23.1 or upgrading to v0.25.1"

**Comment by simoninithomas** [comment]
Hey there 👋 . Thanks for pointing this out 🤗 . Yes we're launching a new version of the course with updates from feedback from students. I'm adding it to the update list.

**Comment by rkrawczyk9** [comment]
Cool! I really appreciate you guys updating this course. Would it be easier if I add small issues like this one as replies to this thread, rather than having new threads?

Because I have another one😆, from Unit 3 Step 2-

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.9.0 requires jedi>=0.10, which is not installed.
thinc 8.1.5 requires typing-extensions<4.2.0,>=3.7.4.1; python_version < "3.8", but you have typing-extensions 4.4.0 which is incompatible.
spacy 3.4.2 requires typing-extensions<4.2.0,>=3.7.4; python_version < "3.8", but you have typing-extensions 4.4.0 which is incompatible.
flask 1.1.4 requires click<8.0,>=5.1, but you have click 8.1.3 which is incompatible.
flask 1.1.4 requires Jinja2<3.0,>=2.10.1, but you have jinja2 3.1.2 which is incompatible.
confection 0.0.3 requires typing-extensions<4.2.0,>=3.7.4.1; python_version < "3.8", but you have typing-extensions 4.4.0 which is incompatible.
```

Looks like requirements.txt needs to be updated to include
* jedi >= 0.10
* 3.7.4 <= typing-extensions < 4.2.0
* 5.1 <= click < 8.0
* 2.10.1 <= Jinja2 < 3.0
